// Copy for DES (TASKS 6.2; UI_SPEC sections 6 and 7 "DES"; look spec 7.3): the hypothesis tear sheet,
// the sealed-window confirmation view and the instrument description. UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy().

export const DES = {
  title: 'Hypothesis description',
  confirmationTitle: 'Sealed confirmation',
  instrumentTitle: 'Futures description',
  emptyTitle: 'Description',
  loading: 'Loading {name}...',
  empty: 'DES needs a hypothesis or an instrument. Type a name then DES, for example {overnight_v0 DES <GO>}.',
  errorPrefix: 'The terminal could not load {name}: {detail}',
  confirmationsError: 'The terminal could not check whether {name} is a sealed-window confirmation: {detail}',
  field: 'Hypothesis',
  bodyLabel: '{name} description',
  tabsLabel: 'Description pages',
  tabs: {
    profile: 'Profile',
    checks: 'Pass checks',
    costs: 'Costs and blocks',
    links: 'Linked runs',
  },
  actions: 'Actions',
  help: 'Help',
  preReg: 'PRE-REG',
  postHoc: 'POST HOC',
  spent: 'SPENT',
  badge: '[{badge}]',
  tag: '[{tag}]',
  specLine: 'spec {sha}',
  shaOk: '[sha ok]',
  shaBad: '[sha MISMATCH]',
  rehashOk: '[re-hash ok]',
  rehashBad: '[re-hash failed]',
  round: 'round {round}',
  roundNone: 'no round',
  hypothesis: 'Hypothesis (verbatim from the spec)',
  passBar: 'Pass bar (verbatim from the spec)',
  passBarNone: 'The spec has no pass bar.',
  more: 'More',
  less: 'Less',
  kpiRow: 'Registered test values',
  headlineNote: 'Read from {path} in the screen JSON.',
  notRecorded: 'not recorded in the registry',
  kpi: {
    n: 'n',
    t: 't',
    p: 'p',
    controlP: 'Control p',
    bonferroni: 'Bonferroni',
    holm: 'Holm',
    bhq: 'BH q',
  },
  kpiDescription: {
    n: 'Observations behind the registered test.',
    t: 'The gating t statistic named in the spec.',
    p: 'One-sided p value of the headline test.',
    controlP: 'p value of the built-in control test.',
    bonferroni: 'Bonferroni-adjusted p value over the registered family.',
    holm: 'Holm-adjusted p value over the registered family.',
    bhq: 'Benjamini-Hochberg q value over the registered family.',
    headline: 'The headline value of the registered test.',
  },
  units: {
    count: 'count',
    ratio: 'ratio',
    probability: 'probability',
  },
  cards: {
    equity: 'Equity',
    checks: 'Pass checks',
    cost: 'Cost ladder',
    registration: 'Registration',
    runs: 'Linked runs',
    summary: 'Round summary: {file}',
    summaryNone: 'Round summary',
  },
  go: '{code} »',
  jumpNames: {
    EQ: 'EQ », equity tear sheet',
    MT: 'MT », multiple-testing view',
    REG: 'REG », registry board',
    GP: 'GP », price chart',
  },
  equityNone: 'No return series is recorded for this hypothesis.',
  equityCost: 'Cost per side',
  costOption: '{n} tick',
  costOptions: '{n} ticks',
  equityLabel: '{label}',
  equityDescriptive: 'descriptive, in-sample, not a registered test',
  equityUnit: 'Unit: {unit}',
  equityBench: 'Benchmark: {bench}',
  equityChart: '{name} equity at {cost} per side',
  checksNone: 'This hypothesis has no pass checks of its own.',
  checksCaption: 'Pass checks of {name}, as recorded in the screen JSON',
  checksColumns: {
    number: 'No.',
    key: 'Key',
    reading: 'Check',
    result: 'Result',
    value: 'Value',
  },
  checkPass: '[PASS]',
  checkFail: '[FAIL]',
  checkValue: 'value',
  checkNone: 'not recorded',
  thresholdNote: 'Thresholds are read from the check names and the pass bar; the registry records no threshold field.',
  dsrLabel: 'Sharpe difference (m - BH)',
  comparators: { ge: '>=', gt: '>', le: '<=', lt: '<', eq: '=' },
  ladderTicks: '{n} ticks',
  ladderTick: '{n} tick',
  costName: '{name} cost ladder',
  blocksName: '{name} blocks',
  ladderCaption: 'Cost ladder of {name}',
  ladderColumns: { cost: 'Cost per side', value: 'Value' },
  ladderNone: 'No cost ladder is recorded for this hypothesis.',
  blocksNone: 'No block values are recorded for this hypothesis.',
  breakEven: 'break-even',
  breakEvenAt: 'Break-even {ticks} ticks per side',
  breakEvenOff: 'Break-even {ticks} ticks per side, beyond the ladder',
  breakEvenNone: 'No break-even cost is recorded.',
  unitLine: 'Unit: {unit}',
  basisLine: 'Basis A, read from the screen JSON, never recomputed',
  registration: {
    registered: 'Registered',
    yes: 'yes',
    no: 'no, a check inside another spec',
    verdict: 'Verdict',
    note: 'Verdict note',
    round: 'Round',
    spec: 'Spec',
    sha: 'Spec sha256',
    screen: 'Screen',
    history: 'Earlier files',
    auxiliaries: 'Auxiliary files',
    family: 'Multiple testing',
    none: '--',
  },
  runsNone: 'No Nautilus run is linked to this hypothesis.',
  runsCaption: 'Nautilus runs linked to {name}',
  runsColumns: { number: 'No.', run: 'Run', open: 'Opens' },
  runOpen: 'RUN',
  openRun: 'Open {run} in RUN',
  confirmationsCaption: 'Sealed-window confirmations of {name}',
  confirmationsNone: 'No sealed-window confirmation tested this hypothesis.',
  sealedCaption: 'Sealed files of {name}',
  sealedNone: 'No sealed file belongs to this hypothesis.',
  sealedColumns: { name: 'File', kind: 'Kind', label: 'Label' },
  spentStrip: 'In-sample against sealed',
  spentLabelFallback: 'spent window, descriptive only',
  spentColumns: { row: 'Test', window: 'Window', n: 'n', p: 'p', alpha: 'Alpha', verdict: 'Verdict' },
  inSample: 'In-sample (registered)',
  inSampleWindow: '2010 to 2021',
  sealedWindow: 'sealed, spent',
  openConfirmation: 'Open {name} in DES',
  confirmation: {
    parent: 'Tested hypothesis',
    alpha: 'Alpha',
    n: 'n',
    p: 'p',
    verdict: 'Verdict',
    spec: 'Spec',
    sha: 'Spec sha256',
    opening: 'Opening',
    openingClosed: 'CLOSED',
    openingOpen: 'open',
    label: 'Label',
    passBarGap: 'This backend does not serve the confirmation spec yet (restart the terminal), so its pass bar is not shown here.',
  },
  instrument: {
    identity: 'Instrument',
    root: 'Root',
    symbol: 'Continuous symbol',
    sector: 'Sector',
    fence: 'In-sample window',
    fenceValue: '{start} to {end} (the fence)',
    gateReads: 'Gate reads by the terminal',
    coverage: 'Data coverage',
    coverageCaption: 'Processed price series of {name}',
    coverageNone: 'No processed price series is listed for {name}.',
    columns: { timeframe: 'Timeframe', variant: 'Variant', file: 'File', rows: 'Rows', first: 'First bar', fence: 'Past the fence' },
    unknown: '{name} is not one of the terminal instruments.',
    specsGap: 'Contract size, tick size, trading hours and roll dates are not served by the terminal.',
    chart: 'Price chart',
    chartNote: 'Daily candles of the vendor series over the last year to 2021-12-31, served through the gate. GP shows other bar sizes, the repaired series and the fills of a run.',
    yes: 'yes',
    no: 'no',
  },
} as const
