// Copy for DES (TASKS 6.2; UI_SPEC sections 6 and 7 "DES"; look spec 7.3): the hypothesis tear sheet,
// the sealed-window confirmation view and the instrument description. UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy().

export const DES = {
  title: 'Hypothesis description',
  confirmationTitle: 'Sealed confirmation',
  instrumentTitle: 'Futures description',
  emptyTitle: 'Description',
  /** The command 99) Help types for DES. */
  helpLine: 'DES HELP',
  loading: 'Loading {name}...',
  empty: 'DES needs a hypothesis or an instrument. Type a name then DES, for example {overnight_v0 DES <GO>}.',
  errorPrefix: 'The terminal could not load {name}: {detail}',
  confirmationsError: 'The terminal could not check whether {name} is a sealed-window confirmation: {detail}',
  field: 'Hypothesis',
  bodyLabel: '{name} description',
  tabsLabel: 'Description pages',
  tabs: {
    profile: 'Profile',
    checks: 'Pass checks',
    costs: 'Costs and blocks',
    links: 'Linked runs',
  },
  actions: 'Actions',
  help: 'Help',
  report: 'Report',
  preReg: 'PRE-REG',
  overlay: 'OVERLAY',
  postHoc: 'POST HOC',
  spent: 'SPENT',
  badge: '[{badge}]',
  tag: '[{tag}]',
  specLine: 'spec {sha}',
  shaOk: '[sha ok]',
  shaBad: '[sha MISMATCH]',
  rehashOk: '[re-hash ok]',
  rehashBad: '[re-hash failed]',
  round: 'round {round}',
  roundNone: 'no round',
  hypothesis: 'Hypothesis (verbatim from the spec)',
  passBar: 'Pass bar (verbatim from the spec)',
  passBarNone: 'The spec has no pass bar.',
  more: 'More',
  less: 'Less',
  kpiRow: 'Registered test values',
  headlineNote: 'Read from {path} in the screen JSON.',
  notRecorded: 'not recorded in the registry',
  kpi: {
    n: 'n',
    t: 't',
    p: 'p',
    controlP: 'Control p',
    bonferroni: 'Bonferroni',
    holm: 'Holm',
    bhq: 'BH q',
  },
  kpiDescription: {
    n: 'Observations behind the registered test.',
    t: 'The gating t statistic named in the spec.',
    p: 'One-sided p value of the headline test.',
    controlP: 'p value of the built-in control test.',
    bonferroni: 'Bonferroni-adjusted p value over the registered family.',
    holm: 'Holm-adjusted p value over the registered family.',
    bhq: 'Benjamini-Hochberg q value over the registered family.',
    headline: 'The headline value of the registered test.',
  },
  units: {
    count: 'count',
    ratio: 'ratio',
    probability: 'probability',
  },
  cards: {
    equity: 'Equity',
    checks: 'Pass checks',
    cost: 'Cost ladder',
    registration: 'Registration',
    runs: 'Linked runs',
    summary: 'Round summary: {file}',
    summaryNone: 'Round summary',
  },
  go: '{code} »',
  jumpNames: {
    EQ: 'EQ », equity tear sheet',
    MT: 'MT », multiple-testing view',
    REG: 'REG », registry board',
    GP: 'GP », price chart',
  },
  equityNone: 'No return series is recorded for this hypothesis.',
  equityCost: 'Cost per side',
  costOption: '{n} tick',
  costOptions: '{n} ticks',
  equityLabel: '{label}',
  equityDescriptive: 'descriptive, in-sample, not a registered test',
  equityUnit: 'Unit: {unit}',
  equityBench: 'Benchmark: {bench}',
  equityChart: '{name} equity at {cost} per side',
  checksNone: 'This hypothesis has no pass checks of its own.',
  checksCaption: 'Pass checks of {name}, as recorded in the screen JSON',
  checksColumns: {
    number: 'No.',
    key: 'Key',
    reading: 'Check',
    result: 'Result',
    value: 'Value',
  },
  checkPass: '[PASS]',
  checkFail: '[FAIL]',
  checkValue: 'value',
  checkNone: 'not recorded',
  thresholdNote: 'Thresholds are read from the check names and the pass bar; the registry records no threshold field.',
  dsrLabel: 'Sharpe difference (m - BH)',
  comparators: { ge: '>=', gt: '>', le: '<=', lt: '<', eq: '=' },
  ladderTicks: '{n} ticks',
  ladderTick: '{n} tick',
  costName: '{name} cost ladder',
  blocksName: '{name} blocks',
  ladderCaption: 'Cost ladder of {name}',
  ladderColumns: { cost: 'Cost per side', value: 'Value' },
  ladderNone: 'No cost ladder is recorded for this hypothesis.',
  blocksNone: 'No block values are recorded for this hypothesis.',
  breakEven: 'break-even',
  breakEvenAt: 'Break-even {ticks} ticks per side',
  breakEvenOff: 'Break-even {ticks} ticks per side, beyond the ladder',
  breakEvenNone: 'No break-even cost is recorded.',
  unitLine: 'Unit: {unit}',
  basisLine: 'Basis A, read from the screen JSON, never recomputed',
  registration: {
    registered: 'Registered',
    yes: 'yes',
    no: 'no, a check inside another spec',
    verdict: 'Verdict',
    note: 'Verdict note',
    round: 'Round',
    spec: 'Spec',
    sha: 'Spec sha256',
    screen: 'Screen',
    history: 'Earlier files',
    auxiliaries: 'Auxiliary files',
    family: 'Multiple testing',
    none: '--',
    tag: 'Tag',
    tagOverlay: 'overlay: in the family, a PASS is not an edge',
    amendments: 'Amendments',
    amendmentsOk: '[bound ok]',
    amendmentsBad: '[NOT bound]',
    amendmentsUnknown: '[binding not recorded]',
  },
  runsNone: 'No Nautilus run is linked to this hypothesis.',
  runsCaption: 'Nautilus runs linked to {name}',
  runsColumns: { number: 'No.', run: 'Run', open: 'Opens' },
  runOpen: 'RUN',
  openRun: 'Open {run} in RUN',
  confirmationsCaption: 'Sealed-window confirmations of {name}',
  confirmationsNone: 'No sealed-window confirmation tested this hypothesis.',
  sealedCaption: 'Sealed files of {name}',
  sealedNone: 'No sealed file belongs to this hypothesis.',
  sealedColumns: { name: 'File', kind: 'Kind', label: 'Label' },
  spentStrip: 'In-sample against sealed',
  spentLabelFallback: 'spent window, descriptive only',
  spentColumns: { row: 'Test', window: 'Window', n: 'n', p: 'p', alpha: 'Alpha', verdict: 'Verdict' },
  inSample: 'In-sample (registered)',
  inSampleWindow: '2010 to 2021',
  sealedWindow: 'sealed, spent',
  openConfirmation: 'Open {name} in DES',
  confirmation: {
    parent: 'Tested hypothesis',
    alpha: 'Alpha',
    n: 'n',
    p: 'p',
    verdict: 'Verdict',
    spec: 'Spec',
    sha: 'Spec sha256',
    opening: 'Opening',
    openingClosed: 'CLOSED',
    openingOpen: 'open',
    label: 'Label',
    passBarGap: 'This backend does not serve the confirmation spec yet (restart the terminal), so its pass bar is not shown here.',
  },
  instrument: {
    identity: 'Instrument',
    root: 'Root',
    symbol: 'Continuous symbol',
    sector: 'Sector',
    fence: 'In-sample window',
    fenceValue: '{start} to {end} (the fence)',
    gateReads: 'Gate reads by the terminal',
    coverage: 'Data coverage',
    coverageCaption: 'Processed price series of {name}',
    coverageNone: 'No processed price series is listed for {name}.',
    columns: { timeframe: 'Timeframe', variant: 'Variant', file: 'File', rows: 'Rows', first: 'First bar', fence: 'Past the fence' },
    unknown: '{name} is not one of the terminal instruments.',
    specsGap: 'Contract size, tick size, trading hours and roll dates are not served by the terminal.',
    chart: 'Price chart',
    chartNote: 'Daily candles of the vendor series over the last year to 2021-12-31, served through the gate. GP shows other bar sizes, the repaired series and the fills of a run.',
    yes: 'yes',
    no: 'no',
    tabsLabel: 'Instrument description pages',
    tabs: { profile: 'Profile', coverage: 'Coverage', notes: 'Notes', contracts: 'Contracts (CT)' },
    contract: 'Contract specifications',
    contractNone: '{name} is not in the frozen universe table, so the terminal has no contract specification for it.',
    venue: 'Exchange',
    units: 'Price units',
    tick: 'Tick',
    tickUsd: 'Tick value',
    pointValue: 'Point value',
    costPerSide: 'Cost per side at 1 tick',
    usd: '{value} USD',
    source: 'Source',
    sourceLine: 'Source: {source}.',
    hours: 'Trading hours',
    related: 'Related dates',
    lastTrading: 'Last trading day rule',
    firstNotice: 'First notice rule',
    rollRule: 'Roll rule',
    nextContract: 'Next contract',
    nextRoll: 'Next roll',
    asOf: 'As of (ET)',
    notes: 'Notes: data caveats',
    notesNone: 'No note is recorded for {name}.',
    monthStrip: 'Contract months and codes',
    listed: 'listed',
    cycleSource: 'Listed months from {source}.',
    cycleNone: 'nq-lab records no listing cycle for {name}; the codes are the standard month letters.',
    inSample: 'In-sample data',
    inSampleValue: '{from} to {to}',
    gateLogged: 'Gate reads logged (caller terminal)',
    gateProcess: 'Gate reads this process',
    loadingInstrument: 'Loading {name}...',
  },
} as const

/** Robustness evidence (roadmap #4; UI_SPEC section 7 DES; ANALYTICS_CATALOG C7): the spec curve, the
 * exposure-shift placebo, leave-one-year-out and per-year stability, volatility quintiles, tails, the
 * recorded subsets and any other numeric section the screen file carries. Every number is the file's own;
 * the terminal never recomputes one and never prints a pass or fail. `{name}` slots are filled by fillCopy(). */
export const DES_ROBUSTNESS = {
  header: 'Robustness evidence recorded in the screen file: it is not the pass bar, nothing is recomputed and it adds no pass or fail.',
  headlineShort: 'H',
  headline: 'Headline rule',
  specTitle: 'Pre-registered variants',
  dsrName: '{name} Sharpe difference (m - BH) by variant, 1 tick',
  alphaName: '{name} alpha by variant, 1 tick',
  negativeLine: '{negative} of {of} recorded variants have a negative Sharpe difference (m - BH) at 1 tick; counted by the terminal from the screen file {tag}.',
  placeboTitle: 'Exposure-shift placebo',
  placeboName: '{name} alpha against the placebo quantiles, 1 tick',
  placeboLine: 'Actual alpha {actual} %/yr sits at percentile {percentile} of {draws} placebo shifts (seed {seed}, shifts of at least {minShift} sessions).',
  actual: 'actual',
  placeboQ: 'placebo {q}%',
  stabilityTitle: 'Leave one year out and per year',
  loyoName: '{name} alpha leaving one year out',
  perYearName: '{name} alpha by year',
  allYears: 'all years',
  quintilesTitle: 'Volatility quintiles',
  tailsTitle: 'Tails',
  managed: 'Managed',
  bh: 'Buy and hold',
  subsetsTitle: 'Recorded subsets',
  subsetUnit: 'Values as the screen file records them; the file does not name their unit.',
  pOmitted: 'p-values recorded for subsets stay in the screen file: the terminal shows none beside a slice (C7).',
  otherTitle: 'Other recorded sections',
  more: '{n} more values in the file.',
  none: 'The screen file records no robustness sections.',
  basisLine: 'Basis A (screen series), {unit}; {tag}.',
  forksTitle: 'Forks of this hypothesis',
  forksNote: 'Forks the terminal can serve: the screen series at each recorded cost (Basis A) and each linked Nautilus run at daily and monthly frequency (Basis B). Intervals as served; Basis A and Basis B never share a ladder.',
  forksA: '{name} Sharpe by screen fork (Basis A)',
  forksB: '{name} Sharpe by run fork (Basis B)',
  forksNoneA: 'No screen fork could be read.',
  forksNoneB: 'No usable linked run.',
  notAvailable: 'not available: {detail}',
  unusable: '{run} [UNUSABLE: BALANCE]: not drawn.',
  capped: '{n} more linked runs are not drawn (at most {max}).',
  unlisted: '{run} is not in the runs list: not drawn.',
  forkOpen: 'Open fork {n} tear sheet',
  cols: {
    no: 'No.',
    variant: 'Variant',
    sharpeM: 'Sharpe m',
    sharpeBh: 'Sharpe BH',
    dsr1: 'Sharpe difference (m - BH), 1 tick',
    dsr2: 'Sharpe difference (m - BH), 2 ticks',
    alpha: 'Alpha %/yr',
    tMin: 't min',
    b: 'b',
    turnover: 'Turnover',
    tradeDays: 'Trade days',
    sessions: 'Sessions',
    year: 'Year',
    n: 'n',
    quintile: 'Quintile',
    sigma2: 'Median variance',
    mean: 'Mean',
    median: 'Median',
    sd: 'SD',
    meanOverVar: 'Mean over variance',
    measure: 'Measure',
    subset: 'Subset',
    t: 't',
    hitRate: 'Hit rate',
    total: 'Total',
    engine: 'Engine',
    basis: 'Basis',
    cost: 'Cost',
    freq: 'Freq',
    run: 'Run',
    flags: 'Flags',
    sharpe: 'Sharpe',
    interval: 'Interval',
    tag: 'Tag',
    state: 'State',
  },
} as const

/** 98) Report on DES: the description as a Markdown file (look spec 7.3). */
export const DES_REPORT = {
  menu: 'Description as Markdown',
  title: '# {name}: hypothesis description',
  source: 'Saved from the nq-lab terminal: the values GET /api/hypotheses/{name} served, as the registry and the screen JSON record them; nothing is recomputed. Basis A, in-sample 2010 to 2021.',
  registration: 'Registration',
  registered: 'Registered',
  verdict: 'Verdict',
  tag: 'Tag',
  round: 'Round',
  spec: 'Spec',
  sha: 'Spec sha256',
  registryOk: 'registry ok',
  registryBad: 'registry MISMATCH',
  rehashOk: 're-hash ok',
  rehashBad: 're-hash failed',
  amendments: 'Amendments',
  amendmentsNone: 'none',
  amendmentsList: '{files} ({ok})',
  amendmentsOk: 'each binds to its spec and result',
  amendmentsBad: 'NOT bound to the spec and result',
  amendmentsUnknown: 'binding not recorded',
  screen: 'Screen',
  tests: 'Registered test values',
  testCols: ['Value', 'Figure', 'Unit', 'Tag'],
  checkCols: ['No.', 'Check', 'Result', 'Value'],
  ladderCols: ['Cost per side', 'Value'],
  blockCols: ['Block', 'Value'],
  blocks: 'Blocks',
  confirmations: 'Sealed-window confirmations',
  none: 'Not recorded in the spec.',
  fileName: '{name}_DES.md',
  done: 'Saved the description as {file}.',
  unavailable: 'This browser cannot save a file here.',
  instrument: {
    title: '# {name}: futures description',
    contract: 'Contract specifications',
    noContract: 'Not in the frozen universe table: no contract specification.',
    pairCols: ['Item', 'Value'],
    symbol: 'Continuous symbol',
    venue: 'Exchange',
    sector: 'Sector',
    units: 'Price units',
    tick: 'Tick',
    tickUsd: 'Tick value',
    pointValue: 'Point value',
    costPerSide: 'Cost per side at 1 tick',
    source: 'Source',
    months: 'Contract months',
    listed: '(listed)',
    cycle: 'Listing cycle source: {source}.',
    hours: 'Trading hours',
    hourCols: ['Item', 'Value', 'Source'],
    related: 'Related dates',
    lastTrading: 'Last trading day rule',
    firstNotice: 'First notice rule',
    rollRule: 'Roll rule',
    nextContract: 'Next contract',
    nextRoll: 'Next roll',
    asOf: 'As of (ET)',
    coverage: 'Data coverage',
    window: 'In-sample data {from} to {to}; the fence allows {start} to {end} (end exclusive).',
    reads: 'Gate reads with caller terminal: {logged} logged, {process} this process.',
    seriesCols: ['Timeframe', 'Variant', 'File', 'Rows', 'First bar', 'Past the fence'],
    notes: 'Notes',
  },
} as const
