// Copy for DQ, data quality (ANALYTICS RI4 and RI5; UI_SPEC 7). UK spelling, no em or en dashes, sentence case.

export const DQ = {
  title: 'Data quality',
  symbolField: 'Symbol',
  paramLabel: 'Data quality settings',
  tabsLabel: 'Data quality views',
  tabs: { calendar: 'Calendar', guards: 'Guard fingerprints' },
  loading: 'Loading the data quality records.',
  failed: 'The data quality records could not be read: {detail}',
  noSymbols: 'No QA or repair record could be read.',
  missing: 'Not read: {files}',
  states: {
    vendor: 'Vendor',
    gated_out: 'Gated out',
    rejected: 'Rejected',
    rebuilt: 'Rebuilt',
    unrepairable: 'Unrepairable',
  },
  stateHelp: {
    vendor: 'served from the vendor bars, never flagged',
    gated_out: 'flagged day of a symbol whose repair failed validation; research drops it',
    rejected: 'rejected by the session gate, no repair record',
    rebuilt: 'rebuilt from trade prints and served in the repaired series',
    unrepairable: 'the repair was tried and failed; research drops it',
  },
  legendLabel: 'Day states',
  heatName: '{symbol} data quality calendar',
  heatSummary: '{symbol} data quality calendar, {first} to {last}: {sessions} sessions; {counts}.',
  countPart: '{label} {n}',
  cellTitle: '{date}: {state}{reason}',
  cellReason: '. {reason}',
  weekday: { 1: 'Mon', 2: 'Tue', 3: 'Wed', 4: 'Thu', 5: 'Fri' },
  tableCaption: '{symbol} sessions by year and state',
  colYear: 'Year',
  colSessions: 'Sessions',
  flaggedHeading: 'Flagged days ({n})',
  flaggedLabel: '{symbol} flagged days',
  flaggedEmpty: 'No flagged day.',
  colDate: 'Date',
  colState: 'State',
  colReason: 'Reason',
  selected: 'Selected {date}: {state}. {reason}',
  noReason: 'No reason recorded.',
  qaHeading: 'QA report, per year',
  qaSource: 'Source: {source}',
  qaNone: 'No per-year QA report for this symbol.',
  colRows: 'Rows',
  colOhlc: 'OHLC violations',
  colDup: 'Duplicate times',
  colContracts: 'Contract changes',
  colGaps: 'RTH days with gaps',
  statusLine: 'Repair {repair}: {status}.',
  whyNot: 'Not repaired: {why}',
  sourceLine: 'Day states from {source}.',
  fenceNote: 'Sessions to {fence} only; nothing after the fence is shown.',
  offCalendar: '{n} recorded days are not weekday sessions and are left off the calendar: {dates}.',
  offCalendarMore: ' and {n} more',
  keysNote: 'Arrow keys move the readout one session, Page Up and Page Down one week, Home and End to the ends.',
  guardsHeading: 'Guard fingerprint status',
  guardsLabel: 'Guard groups',
  guardsTally: '{ok} OK, {mismatch} mismatch, {none} with no record.',
  colGroup: 'Group',
  colKeys: 'Keys',
  colStatus: 'Status',
  colLive: 'Live sha256',
  colRecorded: 'Recorded sha256',
  colRecord: 'Record',
  colChanged: 'Changed keys',
  guardsNote: 'Live: the sha256 of each group in the guard module now. Recorded: the lab’s frozen record of it.',
  guardSelected: '{group}: {status}. Record {record}.{changed}',
  guardChanged: ' Changed keys: {keys}.',
  numberedCalendar: 'Calendar',
  numberedGuards: 'Guard fingerprints',
} as const
