// Copy for EVT, the event study (TASKS Phase 11, UI_SPEC 7). UK spelling, no em or en dashes, sentence case.
// Shared market strings (loading, gate, basis, the warning glyph) are in market.ts.

export const EVT = {
  title: 'Event study',
  instrumentField: 'Instrument',
  paramLabel: 'Event study settings',
  instrument: 'Instrument',
  event: 'Event',
  eventAll: 'All',
  eventOption: '{type} ({n})',
  mode: 'Window',
  modeDaily: 'Daily',
  modeIntraday: 'Intraday',
  before: 'Before',
  after: 'After',
  sessionsOption: '{n} sessions',
  minutesOption: '{n} min',
  events: 'Events',
  eventsValue: '{used} of {listed} complete',
  loading: 'Loading the event study.',
  failed: 'The event study could not be read: {detail}',
  calendarLoading: 'Loading the event calendar.',
  calendarFailed: 'The event calendar could not be read: {detail}',
  notIntraday:
    '{root} has no repaired 1m series, so its 1m data is not validated for intraday work. Intraday windows are open for {symbols}.',
  notDaily: '{root} has no daily series in the 27F universe, so daily windows are not open for it.',
  chartName: '{root} around {event}, {mode}',
  chartModeDaily: '{pre} sessions before to {post} after',
  chartModeIntraday: '{pre} minutes before to {post} after',
  summary:
    '{name}: mean cumulative return over {n} events, from {first} at offset {from} to {end} at offset {to}; band at the last offset {lower} to {upper}.',
  summaryEmpty: '{name}: no complete event window, so no mean path.',
  summarySelected: ' Event {date} shown: {value} at the last offset.',
  mean: 'Mean path',
  band: 'Band, mean ± 1.96 se',
  selected: 'Selected event',
  eventLine: 'Event',
  colOffset: 'Offset',
  colMean: 'Mean',
  colSe: 'Std error',
  colLower: 'Band low',
  colUpper: 'Band high',
  colSelected: 'Selected',
  caption: '{name}, pointwise band from the cross-event standard error, not a band whole paths stay inside',
  xSession: 'Sessions from the event',
  xMinute: 'Minutes from the release',
  endHeading: 'At the last offset ({to})',
  endMean: 'Mean',
  endMedian: 'Median',
  endSd: 'Std dev',
  endSe: 'Std error',
  endShare: 'Above 0',
  endN: 'Events',
  endLabel: 'Distribution of the event paths at the last offset',
  gridLabel: 'Events, {n} rows',
  colDate: 'Date',
  colTypes: 'Releases',
  colTime: 'Time ET',
  colFirst: 'First',
  colEnd: 'Last',
  colStatus: 'Status',
  statusUsed: 'Used',
  statusVoid: 'Void: {reason}',
  gridEmpty: 'No event of this type.',
  selectedNote: 'Event {date} ({types}) drawn over the mean path. Number <GO> on a row picks another.',
  pickNote: 'Number <GO> on a row draws that event over the mean path.',
  units: 'Values: return in percent of the price at the release minute, 2 decimals, signed.',
  unitsDaily: 'Values: cumulative sum of daily returns from the close before the event, in percent, 2 decimals, signed; a sum, so over several sessions it is close to but not exactly the price change.',
  bandNote: 'Band: {note}.',
  source: 'Events: {source}; FOMC check: {check}.',
  exportName: 'evt',
} as const
