// Copy for GlyphScatter (roadmap R8 and R5): a scatter whose points carry a verdict in both shape and
// colour (up triangle, down triangle, ring), with labelled reference lines and an optional y = x
// diagonal. The data summary is the chart's accessible name; the table view repeats every number.
// UK spelling, no em or en dashes. `{name}` slots are filled by fillCopy().

export const GLYPH_SCATTER = {
  summary: '{name}: {n} {points}; {x} from {xmin} to {xmax}, {y} from {ymin} to {ymax}; {kinds}.',
  point: 'point',
  points: 'points',
  kind: '{count} {kind} ({glyph})',
  glyphs: { up: 'triangle up', down: 'triangle down', ring: 'ring' },
  hollow: '; {n} hollow',
  off: ' {n} outside the axis range, drawn at its edge.',
  dropped: ' {n} not drawn (missing, or not positive on a log axis).',
  linesOff: ' Not drawn, outside the axis range: {names}.',
  summaryEmpty: '{name}: no points.',
  colTag: 'Mark',
  colPoint: 'Point',
  colKind: 'Kind',
  kindNotDrawn: '{kind}, not drawn',
  missing: '--',
  caption: '{name}, one row per point',
  offScaleLabel: '{tag} ({value})',
  gallery: {
    log: 'Log p against log p, reversed',
    linear: 'Linear axes with reference lines and an off-scale point',
    logName: 'Fixture p before and after deflation',
    linearName: 'Fixture Sharpe in sample and out of sample',
    pBefore: 'p before',
    pAfter: 'p after',
    sharpeIn: 'Sharpe in sample',
    sharpeOut: 'Sharpe out of sample',
    holds: 'holds',
    lost: 'lost',
    undecided: 'undecided',
    beats: 'beats',
    trails: 'trails',
    flat: 'flat',
    diagonal: 'y = x',
    alphaBefore: 'p before 0.05',
    alphaAfter: 'p after 0.05',
    zero: 'zero',
    hurdle: 'hurdle 0.5',
    strategy: 'Strategy {tag}',
    trades: 'Trades',
    note: 'Note',
    thin: 'thin sample',
  },
} as const
