// Copy for GP and GIP (UI_SPEC sections 7 and 10; look spec 7.6). UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy(). copyRules.test.ts checks it with every other copy module.

export const GP_COPY = {
  titleGp: 'Candle chart',
  titleGip: 'Intraday chart',
  instrument: 'Instrument',
  loadingScreen: 'Loading the chart.',
  openGip: 'Intraday chart of the last session (GIP)',
  openGp: 'Daily chart (GP)',
  gridOn: 'Show the price grid',
  gridOff: 'Hide the price grid',
  rollsOn: 'Show roll markers',
  rollsOff: 'Hide roll markers',
  rolls: 'Rolls',

  paramsLabel: 'Chart parameters',
  rangeStart: 'Range',
  rangeEnd: 'to',
  rangeStartName: 'Range start',
  rangeEndName: 'Range end',
  dateName: 'Date',
  datePlaceholder: '<YYYY-MM-DD>',
  variant: 'Variant',
  fills: 'Fills',
  fillsNone: 'None',
  rangeGroup: 'Time range',
  barGroup: 'Bar size',
  rangeTooLong: '{range}: longer than one {tf} request may span ({years} year)',
  rangeTooLongPlural: '{range}: longer than one {tf} request may span ({years} years)',

  noInstrument: 'No instrument in this panel. Name one with the function, for example NQ GP or NQ GIP 2019-03-14.',
  badSymbol: '{value} is not an instrument the terminal serves.',
  loading: 'Loading bars through the OOS gate.',
  empty: 'No bars were served for {ticker} {tf} {variant} in this window.',
  refusedHeading: 'Gate refused this window.',
  refusedLocal: 'Checked against the gate rule in the terminal; no price request was sent.',
  refusedServer: 'The gate refused the request:',
  errorHeading: 'Bars could not be loaded ({status}):',
  badDate: '{value} is not a date. Use YYYY-MM-DD.',
  startAfterEnd: 'The range start must not be after its end.',
  variantMissing: 'No {variant} series at {tf} for {ticker}; showing vendor.',

  sessionsLabel: 'Session flags',
  gated: 'GATED',
  repaired: 'REPAIRED',
  gatedCount: '{n} sessions rejected by qa.day_gate',
  gatedOne: '1 session rejected by qa.day_gate',
  repairedCount: '{n} sessions rebuilt from trades',
  repairedOne: '1 session rebuilt from trades',
  sessionsNone: 'No gated or repaired session in this window.',
  notAssessed: 'Sessions not assessed: no session QA for this symbol.',
  dayGated: '{date} was rejected by qa.day_gate.',
  dayRepaired: '{date} was rebuilt from trades.',
  dayClean: '{date} passed qa.day_gate.',
  firstDates: 'first {dates}',
  sessionSource: 'source: {source}',

  gate: 'Gate: caller {caller}, served {years}{cached}, reads this process {reads}',
  cached: ' (cached)',
  bucket: 'Bucket {bucket}',
  bucketWidened: 'Bucket {bucket}: {tf} bars widened to fit the point limit',
  basis: 'Prices: {label}; bars stamped at {convention}; not a registered test.',
  rvBasis: 'Change: back-adjusted points against the close before; % change and RV22 (22 sessions, annualised, per cent) from the 27F universe to {date} [POST HOC].',
  rvMissing: 'Change: back-adjusted points against the close before; % change and RV22 only on 1d charts that end on the universe date.',
  rvPane: 'RV22 pane: {label}; {basis}; unit {unit}, shown in per cent.',
  rvPaneMissing: 'No RV22 pane: {detail}',
  fillsNote: '{n} fills from {run}. Fill prices are contract prices; candles are back-adjusted.',
  fillsCapped: 'Showing the first {n} of {total} fills.',
  fillsNoneInRun: 'No fills from {run} for this instrument.',
  fillsError: 'Fills from {run} could not be loaded: {detail}',

  /** nq_lab.oos_gate.check_window's refusal, word for word; the slots are pandas UTC timestamps. */
  gateRule: 'window [{start}, {end}) leaves the in-sample window [{isStart}, {isEnd}); straddling windows are refused, not clipped',
} as const
