// Copy for LIVE's IB snapshot panel (PRD U3, DL5, DL6; ARCHITECTURE section 8). UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy(). The panel only reads: nothing here offers an action on an instruction.

export const IB = {
  screen: 'IB snapshot',
  title: 'IB account snapshot (read only)',
  readOnlyTag: 'READ ONLY',
  loading: 'Reading the IB snapshot.',
  loadError: 'The IB snapshot could not be read: {detail}',
  badBody: 'The IB snapshot reply was not in the expected shape.',

  stateOff: 'IB snapshot off (NQT_IB_READONLY not set)',
  stateOffNote:
    'The terminal does not connect to TWS unless NQT_IB_READONLY=1 is set when it starts. It has no order path either way. {message}',
  stateUnreachable: 'TWS not reachable',
  stateUnreachableNote: 'The read-only snapshot could not reach TWS or IB Gateway: {message} The paper book above is unaffected.',
  stateRefused: 'IB snapshot refused',
  stateRefusedNote: 'A guard stopped the read before anything was sent to TWS: {message} Only a paper account on this machine is ever read.',
  // The state word sits alone in the polite status region; the ticking age is plain text beside it, so a screen reader
  // hears a message when the state changes, not every few seconds as the age grows.
  stateStaleWord: 'STALE',
  stateStaleAge: 'last read {age} ago (current within {limit})',
  stateStaleNote: 'These are the last values TWS reported, not the current account.',
  stateStaleFailed: 'The latest read failed, so these are the last values TWS reported.',
  stateLiveWord: 'Live',
  stateLiveAge: 'read {age} ago',
  stateLabel: 'IB snapshot state',

  stripLabel: 'IB account',
  account: 'Account',
  netLiquidation: 'Net liquidation',
  asOf: 'Read at',
  twsTime: 'TWS clock',
  clientId: 'Client id',
  none: '--',

  positionsTitle: 'Positions',
  positionsLabel: 'IB positions',
  positionsEmpty: 'No open positions reported.',
  workingTitle: 'Open orders (view only)',
  workingLabel: 'IB open orders, view only',
  workingEmpty: 'No open orders reported.',
  executionsTitle: "Today's executions",
  executionsLabel: 'IB executions today',
  executionsEmpty: 'No executions reported today.',

  colSymbol: 'Contract',
  colType: 'Type',
  colExchange: 'Exchange',
  colCurrency: 'Ccy',
  colExpiry: 'Expiry',
  colPosition: 'Position',
  colAvgCost: 'Avg cost',
  colAction: 'Action',
  colKind: 'Kind',
  colQuantity: 'Qty',
  colLimit: 'Limit',
  colStatus: 'Status',
  colFilled: 'Filled',
  colRemaining: 'Left',
  colTime: 'Time',
  colSide: 'Side',
  colShares: 'Shares',
  colPrice: 'Price',
  colCommission: 'Commission',

  incomplete: 'TWS did not finish its reply for: {sections}. Those lists may be missing rows.',
  truncated: 'Some rows were left out to keep the reply small.',
  notes: 'TWS notes: {notes}',
  basisNote: 'Read from TWS with ibapi client id 95: account summary, positions, open orders and executions only.',
  footLabel: 'IB snapshot totals',
  footPositions: 'Positions',
  footWorking: 'Open orders',
  footExecutions: 'Executions',
} as const
