// Copy for the JOBS screen, the backtest queue (ARCHITECTURE section 8; PRD U3, DL5). UK spelling, no em or en
// dashes. `{name}` slots are filled by fillCopy(). No word here, and no name in src/screens/jobs, may match the
// action-name scan (order, submit, cancel, modify): a job is queued and stopped, never "cancelled" or "submitted".

export const JOBS = {
  code: 'JOBS',
  screen: 'Backtest queue',
  title: 'Backtest queue',
  loading: 'Reading the backtest queue.',
  loadError: 'The backtest queue could not be read: {detail}',
  unavailable: 'The backtest runner is not switched on for this server. {detail}',
  runnerOff: 'The backtest runner is off in this mode (a fixture or demo server), so nothing can be queued.',
  basis:
    'In-sample backtests only, from 2010-01-01 to 2021-12-31. A run writes backtests/output/<run id> and its gate log lines, nothing else. Nothing on this screen connects to a broker.',
  counts: 'Running {running}, queued {queued}, capacity {cap}.',
  full: 'The queue is full ({cap} jobs). Wait for one to finish or stop one.',
  fullShort: 'Queue full',

  statuses: {
    queued: 'QUEUED',
    running: 'RUNNING',
    ok: 'OK',
    failed: 'FAILED CHECKS',
    error: 'ERROR',
    stopped: 'STOPPED',
  },
  statusUnknown: 'UNKNOWN {value}',
  exitNone: '--',
  missing: '--',

  table: {
    caption: 'Backtest jobs, newest first',
    empty: 'No jobs yet. Queue one with the form above.',
    cols: {
      run: 'Run id',
      strategy: 'Strategy',
      variant: 'Variant',
      window: 'Window',
      status: 'Status',
      exit: 'Exit',
      queued: 'Queued (UTC)',
      started: 'Started (UTC)',
      finished: 'Finished (UTC)',
      actions: 'Actions',
    },
  },
  row: {
    view: 'View log',
    viewLabel: 'View log for {runId}',
    open: 'Open in RUN',
    openLabel: 'Open in RUN for {runId}',
    stop: 'Stop',
    stopLabel: 'Stop the job {runId}',
    confirm: 'Stop {runId}?',
    confirmYes: 'Yes, stop it',
    confirmKeep: 'Keep it',
    stopped: 'Stop requested for {runId}.',
    stopFailed: 'The job {runId} could not be stopped: {detail}',
  },

  form: {
    legend: 'Queue a backtest',
    strategy: 'Strategy',
    variant: 'Data variant',
    start: 'Start',
    end: 'End (exclusive)',
    runId: 'Run id',
    runIdHint: 'Starts with t_, then 1 to 80 characters from A to Z, a to z, 0 to 9, the sign _, a dot or a hyphen.',
    params: 'Parameters (a JSON object)',
    paramsHint: 'Only the keys the chosen strategy declares are accepted. The server checks them again.',
    windowHint: 'In-sample window: from 2010-01-01, to 2022-01-01 (exclusive).',
    queue: 'Queue run',
    queuing: 'Queuing the run.',
    queued: 'Queued {runId}.',
    notQueued: 'Not queued: {detail}',
    problems: 'Fix {n} problem before the run can be queued.',
    problemsMany: 'Fix {n} problems before the run can be queued.',
    errorPrefix: 'Error:',
  },

  errors: {
    strategy: 'Choose one of the listed strategies.',
    variant: 'Choose one of the listed data variants.',
    paramsInvalid: 'The parameters are not valid JSON: {detail}',
    paramsNotObject: 'The parameters must be a JSON object, for example {"ticks": 1}.',
    startFormat: 'Write the start as a real date, YYYY-MM-DD.',
    startBefore: 'The start may not be before 2010-01-01.',
    endFormat: 'Write the end as a real date, YYYY-MM-DD.',
    endAfter: 'The end may not be after 2022-01-01.',
    frozenSpan: 'This strategy runs only on its frozen span: the repaired variant from 2010-01-01 to 2022-01-01.',
    endNotAfterStart: 'The end must be after the start.',
    runIdFormat: 'The run id must be t_ followed by 1 to 80 characters from A to Z, a to z, 0 to 9, the sign _, a dot or a hyphen.',
    runIdTaken: 'A job or a run already uses this id. Every run needs a fresh id.',
  },

  log: {
    heading: 'Log tail of {runId}',
    label: 'Log tail of {runId}',
    none: 'Choose a job to read the tail of its log.',
    empty: 'No output yet.',
    loading: 'Reading the log.',
    loadError: 'The log could not be read: {detail}',
    lines: 'The last {n} lines.',
    section: 'Job log',
  },
} as const
