// Copy for the Start from flow (LEDG and RUN launch a backtest through the JOBS queue). UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy(). No word here may match the action-name scan (order, submit, cancel,
// modify): a run is launched, queued and stopped, never "submitted" or "cancelled".

export const LAUNCH = {
  menu: {
    marked: 'Start a run from the marked row',
    newest: 'Start a run from the newest row',
    run: 'Start a run from this run',
  },
  noSeed: 'This row does not record its strategy, data variant and window, so a run cannot be started from it.',
  heading: 'Start a run from {label}',
  region: 'Start a run',
  basis:
    'In-sample backtest of a registered strategy, queued in JOBS. Nothing here writes the ledger or connects to a broker.',
  presetLabel: 'Start from',
  presetSelf: '{label} (this one)',
  presetItem: '{label}',
  presetHint: 'Choosing another preset replaces the whole form and discards your edits.',
  presetPicked: 'Form reset to {label}. Your edits were discarded.',
  presetText: '{name}, {strategy}, {variant}, {start} to {end}',
  strategy: 'Strategy',
  variant: 'Data variant',
  start: 'Start',
  end: 'End (exclusive)',
  runId: 'Run id',
  runIdHint: 'A fresh id, suggested from the preset. It starts with t_.',
  windowHint: 'In-sample window: from 2010-01-01, to 2022-01-01 (exclusive).',
  params: 'Parameters',
  paramsNone: 'This strategy declares no parameters.',
  paramNote: 'Not described by the server.',
  changed: 'CHANGED from the preset ({was})',
  changedNone: 'not set',
  yes: 'yes',
  no: 'no',
  flagOn: 'Yes',
  specUnknown: 'Starting from {name}.',
  notPreset: 'This run is not a launch preset (only ledger rows of registered strategies are), so a run cannot be started from it.',
  notLaunchable: 'This preset cannot be launched as it stands: {reasons}',
  needsPresets: 'The preset list is needed to launch, and it is not available.',
  variantFixed: 'Fixed by the preset.',
  offSpec: 'OFF SPEC: this run differs from the preset. It is a warning, not a block.',
  onSpec: 'On spec: this run repeats the preset exactly.',
  summary: '{strategy}, {variant} data, {start} to {end}, run {runId}. {changes}',
  changesNone: 'No parameter differs from the preset.',
  changesOne: '1 parameter differs from the preset.',
  changesMany: '{n} parameters differ from the preset.',
  launch: 'Launch',
  launching: 'Launching the run.',
  close: 'Close',
  keys: 'Enter launches, Escape closes, Left and Right move between the fields.',
  problems: 'Fix {n} problem before the run can be launched.',
  problemsMany: 'Fix {n} problems before the run can be launched.',
  errorPrefix: 'Error:',
  runnerOff: 'The backtest runner is off in this mode (a fixture or demo server), so a run cannot be launched.',
  queueFull: 'The queue is full ({cap} jobs). Wait for one to finish, or stop one in JOBS.',
  notLaunched: 'Not launched: {detail}',
  failedFallback: 'The request failed.',
  queued: 'Queued {runId}. It runs in the backtest queue.',
  messageQueued: 'Queued {runId}. Progress is in JOBS.',
  openJobs: 'Open JOBS',
  another: 'Start another',
  presetsFailed: 'The preset list could not be read ({detail}). The parameters come from this run alone, without ranges.',
  presetsLoading: 'Reading the parameter ranges.',
  errors: {
    strategy: 'This run uses a strategy that is not a registered strategy of the queue, so a run cannot be started from it.',
    needsValue: '{name} needs a value.',
    wholeNumber: '{name} must be a whole number.',
    number: '{name} must be a number.',
    between: '{name} must be between {min} and {max}.',
    atLeast: '{name} must be at least {min}.',
    atMost: '{name} must be at most {max}.',
    above: '{name} must be above {min}.',
    aboveAtMost: '{name} must be above {min} and at most {max}.',
    oneOf: '{name} must be one of {choices}.',
    flag: '{name} must be yes or no.',
    text: '{name} may hold letters, digits and _ . : + - only, 1 to 64 characters.',
    list: '{name} must be a JSON list, for example [1, 2].',
    listItems: '{name} may hold numbers, flags and short text only.',
    listLong: '{name} may hold at most 64 items.',
  },
  hint: {
    int: 'Whole number',
    float: 'Number',
    bool: 'Yes or no',
    text: 'Short text',
    oneOf: 'One of {choices}',
    list: 'A JSON list, for example [1, 2]',
    rangeBetween: ', {min} to {max}',
    rangeAtLeast: ', at least {min}',
    rangeAtMost: ', at most {max}',
    rangeAbove: ', above {min}',
    rangeAboveAtMost: ', above {min}, at most {max}',
    rangeNone: ', no range declared',
    required: 'Required.',
    defaultIs: 'Default {value}.',
    defaultNone: 'No default.',
  },
} as const
