// Copy for the LIVE and JRNL screens (TASKS 7.3; UI_SPEC section 7 LIVE and JRNL; look spec 7.11;
// ANALYTICS_CATALOG LV1 to LV4). UK spelling, no em or en dashes. `{name}` slots are filled by fillCopy().

export const LIVE = {
  screen: 'Paper book',
  title: 'Paper book (read only)',
  loading: 'Reading the paper book status.',
  loadError: 'The paper book status could not be read: {detail}',
  stateLabel: 'Paper book state',
  guardLabel: 'Guards and environment',
  contract: 'Contract',
  lastClose: 'Last close',
  noClose: 'no performance close row yet',
  target: 'Target',
  actual: 'Held',
  expected: 'Expected',
  exposure: 'Exposure',
  exposureUnit: 'notional / equity',
  slippage: 'Slippage',
  ticks: '{n} ticks',
  closePx: 'Close',
  closePxUnit: 'pts',
  contracts: '{n} ct',
  sent: 'Sent',
  refused: 'Refused',
  blocked: 'Blocked',
  reconciled: 'Reconciled',
  error: 'Error',
  halted: 'Halted',
  kill: 'KILL',
  killOn: '[on]',
  killOff: '[off]',
  killFile: 'kill switch file {path}',
  delayed: 'Delayed flag',
  volmanC: 'VOLMAN_C',
  baseRate: 'IB_BASE_USD_RATE',
  ib: 'IB',
  account: 'Account',
  tws: 'TWS',
  orderPath: 'Order path',
  set: 'set',
  unset: 'not set',
  yes: 'yes',
  no: 'no',
  ok: 'ok',
  fail: 'FAIL',
  none: '--',
  hostPort: '{host}:{port}',
  lastJournalRow: 'Journal written',
  lastLogLine: 'Log written',
  basisNote: 'Basis B: paper account values read from the book journal, performance rows only (plumbing rows dropped).',
  kpiLabel: 'Book exposure summary',
  kpiMeanExposure: 'Mean exposure',
  kpiMeanExposureDesc: "Mean of the book journal's close-row exposure (notional over equity), from paper_plumbing.exposure_summary; descriptive.",
  kpiSessions: 'Sessions',
  kpiSessionsDesc: 'Close rows counted by paper_plumbing.exposure_summary.',
  kpiPlumbing: 'Plumbing rows dropped',
  kpiPlumbingDesc: 'Rows labelled plumbing test, delayed data, left out of every performance view.',
  unitX: 'x equity',
  unitCount: 'count',
  chartTitle: 'Target against actual, {journal}',
  chartTargetSeries: 'Target (ct)',
  chartActualSeries: 'Held (ct)',
  chartExposureSeries: 'Exposure (notional / equity)',
  chartLoading: 'Checking the performance rows against the journal.',
  chartEmpty: 'No performance close rows yet.',
  chartNoDates: '{n} close rows without a date are left out of the chart.',
  guardMismatch: "Not drawn: the performance rows do not match the journal's non-plumbing close rows ({perf} against {journal}).",
  guardOrder: 'Not drawn: the performance dates are not in order.',
  guardUnverified: 'Not drawn: the journal has more close rows than one page, so the rows cannot be checked.',
  plumbingSkipped: 'Plumbing rows dropped from this view: {n}.',
  reconLabel: 'Reconciliation, performance rows only',
  colDate: 'Date',
  colContract: 'Contract',
  colTarget: 'Target',
  colExpected: 'Expected',
  colActual: 'Held',
  colReconciled: 'Recon',
  colExposure: 'Exposure',
  colSlippage: 'Slip (ticks)',
  colSent: 'Sent',
  colRefused: 'Refused',
  colError: 'Error',
  colHalted: 'Halted',
  journalsLabel: 'Journals under live/logs',
  colJournal: 'Journal',
  colRows: 'Rows',
  colPlumbingRows: 'Plumbing',
  colPerformanceRows: 'Performance',
  colLastType: 'Last type',
  colLastDate: 'Last date',
  colBadLines: 'Bad lines',
  plumbingTag: '[PLUMBING]',
  expectedMissing: 'expected',
} as const

export const JRNL = {
  screen: 'Journals',
  title: 'Journals',
  fileField: 'File',
  allFiles: 'All journals',
  missingFile: '{name} (not yet written)',
  plumbingFile: '{name} [PLUMBING]',
  typeField: 'Type',
  allTypes: 'All types',
  paramsLabel: 'Journal filters',
  loading: 'Reading the journal.',
  error: 'The journal could not be read: {detail}',
  noJournals: 'No journals yet.',
  noRows: 'No rows of this type in {file}.',
  noRowsAny: 'No rows in {file}.',
  allFilesName: 'every journal in live/logs',
  rowsShown: 'Rows {shown} of {total}.',
  plumbingNote: 'Plumbing rows are hatched and carry the banner; they are never strategy performance.',
} as const
