// Copy for the OOS screen (TASKS 7.3; UI_SPEC section 7 OOS; look spec 7.10; ANALYTICS_CATALOG RI2).
// UK spelling, no em or en dashes. `{name}` slots are filled by fillCopy().

export const OOS = {
  screen: 'Gate access log and openings',
  title: 'Gate access log',
  // U07: 'out-of-sample' appeared nowhere, and 'A', 'R' and 'house' went unexplained.
  subtitle: 'OOS: out-of-sample gate access log',
  hintAlert: 'A: alert flag. Set for a sealed read or a window the gate would refuse.',
  hintSeverity: "R: house severity 1 to 4, this project's own scale. The key above says what each level means.",
  allCallers: 'All callers',
  callerField: 'Caller',
  callerOption: '{caller} ({n})',
  sinceField: 'Since',
  sincePlaceholder: '<YYYY-MM-DD>',
  viewLabel: 'View',
  viewLog: 'Log',
  viewTimeline: 'Timeline',
  paramsLabel: 'Access log filters',
  countsLabel: 'Access log counts',
  terminalReads: 'Terminal reads {n}',
  sealedReads: 'Sealed reads {n}',
  totalReads: 'Log lines {n}',
  matched: 'Matched {n}',
  showing: 'Showing the newest {shown} of {matched}',
  partialTail: 'The last line is still being written and is not shown yet.',
  parseErrors: 'Exceptions ({n}): lines the parser could not read',
  noLog: 'No access log yet: results/oos_access_log.jsonl',
  empty: 'No gate reads match these filters.',
  loading: 'Reading the access log.',
  error: 'The access log could not be read: {detail}',
  gridLabel: 'Gate access log entries, newest first',
  colTime: 'Time (UTC)',
  colAlert: 'A',
  colSeverity: 'R',
  colCaller: 'Caller',
  colReason: 'Reason',
  colSymbol: 'Symbol',
  colTimeframe: 'TF',
  colVariant: 'Variant',
  colWindow: 'Window',
  colRows: 'Rows',
  colResult: 'Result',
  alertGlyph: '⚑',
  alertSealed: 'sealed read',
  alertPast: 'window past the fence',
  alertCheck: 'window the gate would refuse, or unreadable',
  severityText: 'severity {level} of {max}',
  severityMeaning: 'severity {level} of {max}: {meaning}',
  severityLegendLabel: 'Severity levels (house semantics) with their counts over the whole log',
  severityLegendTitle: "R: house severity (this project's own scale):",
  severityLegendItem: '{level} {meaning}: {n}',
  resultServed: 'served [IS]',
  resultSealed: 'SEALED READ',
  resultPast: 'PAST FENCE',
  windowText: '{start}..{end}',
  timelineName: 'OOS gate reads by caller',
  timelineSkipped: '{n} entries without a readable window are left out of the timeline.',
  sinceInvalid: 'Since takes a date as YYYY-MM-DD.',
  exportDone: 'Saved {n} access log entries as CSV.',
  exportEmpty: 'Nothing to export.',
  exportUnavailable: 'This browser cannot save a file here.',
  exportFile: 'oos_access_log_view.csv',
} as const

/**
 * U07: the DES link from a hypothesis to its gate reads, with the count the gate log holds for it. The count is for
 * the exact caller name the link asks for (a caller is recorded, never inferred from a name stem), and a screen may
 * log its reads under its own caller name (za_v0 reads as za_screen), so the words say what was asked.
 */
export const OOS_LINK = {
  link: 'Gate reads (OOS) for this hypothesis',
  readsOne: '1 read logged as caller {caller}',
  reads: '{n} reads logged as caller {caller}',
  none: 'no reads logged as caller {caller} (a screen may log its reads under its own caller name)',
} as const

export const OPENINGS = {
  label: 'Sealed window openings',
  title: 'Openings',
  none: 'No openings recorded: results/oos_openings.json',
  loading: 'Reading the openings.',
  error: 'The openings could not be read: {detail}',
  opened: 'opened {date} by {by}',
  closedTag: 'CLOSED',
  openTag: 'OPEN',
  closedAt: 'closed {date}',
  caller: 'caller {caller}',
  window: 'window {start}..{end}',
  symbols: 'symbols {symbols}',
  pinOk: 'openings pin ok',
  pinBad: 'openings pin FAILED',
  pinUnknown: 'openings pin unknown',
  logPinOk: 'sealed log pin ok',
  logPinBad: 'sealed log pin FAILED',
  logPinUnknown: 'sealed log pin unknown',
  sealedLines: 'sealed lines {lines} of {pinned} pinned',
  spentTag: '[SPENT]',
} as const
