// Copy for the Perspective pivot views (TASKS 9.1): RUN trades and fills, the LEDG pivot and the OOS log.
// UK spelling, no em or en dashes. `{name}` slots are filled by fillCopy().

export const PIVOT = {
  viewLabel: 'View',
  grid: 'Grid',
  pivot: 'Pivot',
  /** The accessible name of the viewer's own region: what it holds and how many rows. */
  region: '{name}, {rows} rows, pivot grid',
  loadingEngine: 'Starting the pivot engine.',
  loadingRows: 'Reading {name}: {n} of {total} rows.',
  loadingAll: 'Reading {name}.',
  ready: '{rows} rows in the pivot grid.',
  failed: 'The pivot grid could not start: {detail}',
  engineTimeout: 'the pivot engine did not start within 20 seconds',
  readFailed: '{name} could not be read: {detail}',
  tag: '[POST HOC]',
  note: 'Group, split, sort and filter here are worked out in this page from the rows the API sent; totals and averages are descriptive only, and no p-value is shown for a slice picked here.',
  keys: "Tab reaches the grid; arrow keys, Page Up and Page Down scroll it; Tab again moves into the grid's own controls and Escape brings focus back.",
  /** The accessible table every pivot view also offers (the same rows, the pivot grid's opening layout). */
  show: 'Show as',
  showTable: 'Table',
  showPivot: 'Pivot grid',
  table: {
    label: '{name}, {rows} rows, table',
    ready: 'Table of {name}: {rows} rows.',
    flatNote: "Every row the API sent, in the pivot grid's opening columns and order. Arrow keys move the cell; Enter on a header sorts by it.",
    groupedNote: "Grouped by {group}, as the pivot grid opens: a total row, then one row per {group}; each header names its aggregate. Arrow keys move the cell; Enter on a header sorts by it.",
    reducedMotion: 'Opened as a table because this browser asks for reduced motion; Pivot grid switches to the interactive grid.',
    fallback: 'The pivot grid could not start ({detail}), so the same rows are shown as a table.',
    total: 'Total',
    totalSection: 'All rows',
    groupSection: 'Groups',
    noValue: '(no value)',
    yes: 'Yes',
    no: 'No',
    aggregates: {
      sum: 'sum',
      count: 'count',
      distinct: 'distinct',
      highest: 'highest',
      latest: 'latest',
    },
  },
  names: {
    fills: 'Fills of {run}',
    trades: 'Trades of {run}',
    ledger: 'Run ledger',
    oos: 'Gate access log',
  },
  fills: {
    ts: 'Time (UTC)',
    instrument: 'Instrument',
    side: 'Side',
    qty: 'Qty',
    px: 'Price',
    commission: 'Commission',
    position: 'Position id',
    order: 'Order ref',
    tags: 'Tags',
  },
  trades: {
    date: 'Date',
    side: 'Side',
    entryTs: 'Entry (UTC)',
    entryPx: 'Entry price',
    exitTs: 'Exit (UTC)',
    exitPx: 'Exit price',
    reason: 'Exit reason',
    pnlPts: 'P&L (points)',
    pnlUsd: 'P&L (USD)',
    commissions: 'Commissions (USD)',
    netR: 'Net R',
    long: 'Long',
    short: 'Short',
  },
  ledger: {
    ts: 'Written (UTC)',
    runId: 'Run id',
    expId: 'Exp id',
    strategy: 'Strategy',
    start: 'Start',
    end: 'End',
    trades: 'Trades',
    pnl: 'Net P&L (USD)',
    fees: 'Fees (USD)',
    hitRate: 'Hit rate',
    meanNetR: 'Mean net R',
    tNetR: 't (net R)',
    balance: 'Balance',
    matches: 'Matches result.json',
    runtime: 'Runtime (s)',
  },
  oos: {
    ts: 'Time (UTC)',
    caller: 'Caller',
    reason: 'Reason',
    symbol: 'Symbol',
    timeframe: 'Timeframe',
    variant: 'Variant',
    start: 'Window start',
    end: 'Window end',
    rows: 'Rows served',
    severity: 'Severity',
    sealed: 'Sealed read',
    alert: 'Alert',
    line: 'Log line',
  },
} as const
