// Copy for the REG (registry board) and MT (multiple-testing) screens (UI_SPEC 7 and 10; look spec 7.2).
// UK spelling, no em or en dashes, sentence case; tags and verdict badges keep their upper case.

export const REG = {
  title: 'Registry board',
  gridLabel: 'Registry board: every registry row',
  filterLabel: 'Filter hypotheses by name',
  filterPlaceholder: '<Filter by name>',
  loading: 'Reading the registry.',
  failed: 'The registry could not be read: {detail}',
  cardsFailed: 'The hypothesis cards could not be read ({detail}): verdicts come from the registry text; rounds and re-hash status are unknown.',
  empty: 'No registry row matches the filter.',
  railLabel: 'Rounds',
  railHeading: 'Rounds',
  allRounds: 'All rounds',
  round: 'Round {n}',
  noRound: 'No round',
  railItem: '{label} ({count})',
  criteriaLabel: 'Screening criteria',
  criteriaHeading: 'Selected screening criteria',
  criteriaSource: 'values read from results/registry.csv through the API',
  matches: 'Matches',
  criteria: {
    rows: 'Registry rows',
    registered: 'Registered hypotheses',
    edges: 'Edge hypotheses',
    overlays: 'Risk overlays (in the family, not edges)',
    passed: 'Passed own bar',
    passedEdges: 'Edges that passed their bar',
    failed: 'Failed own bar',
    checks: 'Check rows, no own bar',
    bh: 'BH q below {alpha}',
  },
  criterionItem: '{n}) {label} {count}',
  compact: 'Registered {registered}  Pass {passed}  Fail {failed}  Check {checks}  BH q<{alpha} {bh}',
  cols: {
    name: 'Name',
    round: 'Round',
    verdict: 'Verdict',
    n: 'n',
    p: 'p',
    controlP: 'Ctrl p',
    bonferroni: 'Bonf',
    holm: 'Holm',
    bhQ: 'BH q',
    sha: 'Spec sha',
    hash: 'Hash ok',
    tag: 'Tag',
    amendments: 'Amend',
  },
  tags: { edge: 'edge', overlay: '[OVERLAY]', check: 'check' },
  amend: { ok: 'ok', bad: 'NO' },
  accept: {
    label: 'Accepted amendments',
    heading: 'Accepted amendments',
    line: 'Accepted {utc} from {source}: {n} amendments, {state}.',
    allUnchanged: 'all unchanged',
    changed: '{n} CHANGED since acceptance',
    none: 'No amendment acceptances recorded: {source}',
    cols: { file: 'File', spec: 'Amends', rows: 'Registry rows', accepted: 'Sha accepted', now: 'Sha now', unchanged: 'Unchanged' },
    yes: 'yes',
    no: 'CHANGED',
  },
  compactNote: 'Columns hidden here (maximise the panel to see them): round, control p, Bonferroni, spec sha. 98) Export saves every column.',
  overlayNote: '[OVERLAY]: a registered risk overlay, in the multiple-testing family, but its PASS is not an edge.',
  notesLabel: 'Verdict notes',
  noteSeparator: ': ',
  hash: { ok: 'ok', registry: 'NO: registry', rehash: 'NO: re-hash', both: 'NO: both' },
  actions: {
    openMt: 'Multiple testing (MT)',
    openDes: 'Open {name} DES',
  },
  settings: {
    hideChecks: 'Hide check rows',
    showChecks: 'Show check rows',
    clear: 'Clear filters',
  },
  export: {
    csv: 'Registry as CSV',
    fileName: 'registry_board.csv',
    done: 'Registry saved as {file}.',
    unavailable: 'This browser cannot save a file here.',
  },
} as const

export const CONFIRM = {
  label: 'Sealed confirmations, own alpha, outside the family',
  heading: 'Sealed confirmations',
  note: 'Each has its own alpha and is not part of the multiple-testing family.',
  empty: 'No sealed confirmation is recorded.',
  failed: 'The sealed confirmations could not be read: {detail}',
  spent: 'SPENT',
  cols: {
    name: 'Name',
    parent: 'Tests',
    n: 'n',
    p: 'p',
    alpha: 'Own alpha',
    verdict: 'Verdict',
    sha: 'Spec sha',
    hash: 'Sha ok',
    opening: 'Opening',
    label: 'Window',
  },
  closed: 'CLOSED',
  open: 'OPEN',
  ownAlpha: 'own alpha {alpha}',
} as const

export const MT = {
  title: 'Multiple testing',
  familyLabel: 'Multiple-testing family',
  loading: 'Reading the multiple-testing family.',
  failed: 'The multiple-testing family could not be read: {detail}',
  chartName: 'Registry p-values against rank',
  chartId: 'mt-pscatter',
  gridLabel: 'Adjusted p-values by rank',
  empty: 'No registered p-value.',
  family: 'Family k {k}, alpha {alpha}.',
  stored: 'Stored adjusted values match the recomputation (max abs diff {diff}).',
  storedDiffer: 'Stored adjusted values DIFFER from the recomputation (max abs diff {diff}).',
  linesOk: 'Boundary lines match the API at every rank.',
  linesDiffer: 'Boundary lines DIFFER from the API (max abs diff {diff}, first at {name}).',
  storedTag: 'PRE-REG',
  storedTagNote: 'adjusted values stored in the registry',
  computedTag: 'POST HOC',
  computedTagNote: 'recomputed by the terminal as a check; boundaries alpha/k, alpha/(k-i+1) and i alpha/k',
  cols: {
    rank: 'Rank',
    name: 'Name',
    p: 'p',
    bonferroniLine: 'Bonf line',
    holmLine: 'Holm line',
    bhLine: 'BH line',
    bonferroni: 'Bonf',
    holm: 'Holm',
    bhQ: 'BH q',
    passes: 'Under line',
    tag: 'Tag',
  },
  confirmItem: 'opening {opening}, p {p}, n {n}, {alpha}',
  actions: { openReg: 'Registry board (REG)' },
  settings: { log: 'Log p axis', linear: 'Linear p axis' },
} as const
