// Copy for the P2 panels: RG2 trend regime, EX5 capacity and MV6 term structure (TASKS Phase 12; ANALYTICS_CATALOG
// sections 9 to 11). UK spelling, no em or en dashes, sentence case. `{name}` slots are filled by fillCopy(). Every
// panel is descriptive and carries the API's own [POST HOC] tag; no panel shows a p-value.

export const RCT = {
  missing: '--',
  loading: 'Loading.',
  failed: 'Could not be read: {detail}',
  notShown: 'Not shown: {note}',
  gate: 'Prices through the OOS gate, caller {caller}; years served {years}; {cached}.',
  gateCached: 'from the cache',
  gateFresh: 'read now',
  trend: {
    title: 'Trend regime (RG2)',
    caption: 'NQ above or below its 200-session mean, known the session before',
    cols: { regime: 'Regime', n: 'Sessions', mean: 'Mean', sharpe: 'Sharpe', hit: 'Hit rate' },
    names: { above: 'Above the mean', below: 'Below the mean' } as Readonly<Record<string, string>>,
    welch: 'Welch t, above against below: {t} (df {df}).',
    welchNone: 'Welch t, above against below: not defined (fewer than two sessions on one side).',
    noP: 'No p-value: a fixed split, still [POST HOC].',
    unlabelled: 'Sessions without a regime (fewer than {window} earlier closes): {n}.',
    unit: 'Mean in {unit}; Sharpe annualised over 252 sessions.',
    source: 'Source: {source}.',
    chart: {
      title: 'NQ close against its 200-session mean',
      closeName: 'NQ close, back-adjusted',
      meanName: '200-session mean',
      ribbonName: 'Trend regime',
      glyphs: { below: 'B', above: 'A', unused: '-' },
      unused: 'Not used',
      noRegime: 'no regime (fewer than 200 earlier closes)',
      note: 'Both lines are the values at the session before each date, so the strip shows what was known at that date.',
      empty: 'No session of this series has a regime to draw.',
      /** EQ and DD: the strip of the market context may show this regime in place of RG1's. */
      stripToggle: 'Regime strip',
      stripVolatility: 'Volatility',
      stripTrend: 'Trend',
      stripNote: 'Strip under the time axis: RG2 trend regime of each session; {labelled} of {n} sessions labelled. {label} {tag}',
      stripNone: 'No trend regime is served for this series: {note}',
      noReason: 'the API gives no reason',
    },
  },
  capacity: {
    title: 'Capacity (EX5)',
    unit: 'Participation: {unit}.',
    source: "Contracts counted from the run's {source}.",
    sourceNames: { fills: 'fills', trades: 'trades (one contract at each entry and each exit)' } as Readonly<Record<string, string>>,
    instrumentsCaption: 'Traded instruments and the series whose volume measures them',
    instrumentCols: { instrument: 'Instrument', symbol: 'Volume series', factor: 'Full contracts each', note: 'Note' },
    outside: 'none',
    rowsCaption: "Contracts per session over the session's volume, per series",
    rowsRegion: 'Capacity by series',
    rowCols: {
      symbol: 'Series',
      sessions: 'Sessions traded',
      void: 'Void',
      contracts: 'Contracts per session',
      mean: 'Mean',
      median: 'Median',
      p95: '95th pct',
      max: 'Largest',
      maxDate: 'On',
      volume: 'Median volume',
    },
    voidNote: 'Void: a traded session with no volume bar, or a volume of zero or less. It is counted, never dropped.',
    worstCaption: 'Sessions with the largest participation',
    worstRegion: 'Largest sessions',
    worstCols: { date: 'Session', symbol: 'Series', contracts: 'Contracts', volume: 'Volume', ratio: 'Participation' },
    max: 'Largest participation: {ratio} of {symbol} volume.',
    none: 'No traded session has a volume to compare with.',
  },
  term: {
    title: '{root} term structure (MV6)',
    summary: '{n} sessions from the calendar chain; carry mean {mean}, median {median}, range {min} to {max} a year; backwardation on {share} of sessions; last {last} on {lastDate}.',
    summaryNone: 'No session with both the front and the next contract priced.',
    unit: 'Carry in percent a year, positive in backwardation (the front above the next).',
    expirySource: 'Expiries: {source}.',
    ranks: 'Chain ranks served: {ranks}.',
    void: 'Sessions left out: {missingFront} without a front bar, {missingNext} without a next bar, {unresolved} with an unresolved contract, {order} out of expiry order, {thin} thin (volume under 10 or no range), {price} without a positive next price.',
    fenced: 'Rows dated on or after 2022-01-01 dropped: {n}.',
    chart: {
      title: '{root} calendar-chain carry and spread',
      carryName: 'Carry, % a year',
      spreadName: 'Front less next, {units}',
      empty: '{root}: no session with both the front and the next contract priced.',
    },
    curveCaption: 'Latest curve on {date}, every chain rank',
    curveNone: 'No curve: the front has no in-sample bar.',
    curveCols: { rank: 'Rank', contract: 'Contract', expiry: 'Expiry', days: 'Days to expiry', close: 'Close', volume: 'Volume', thin: 'Thin' },
    thinYes: 'thin',
    thinNo: '',
    missingRanks: 'Ranks without a bar that day: {ranks}.',
  },
} as const
