// Copy for ROLL, the roll calendar (UI_SPEC section 5, P1; ANALYTICS MV10, gaps as MV2). UK spelling, no em or en
// dashes, sentence case. `{name}` slots are filled by fillCopy(). Shared market strings (gate, basis,
// the [POST HOC] tag) are in market.ts.

export const ROLL = {
  title: 'Roll calendar',
  universeField: 'Universe',
  tabsLabel: 'Roll calendar views',
  tabCalendar: 'Calendar',
  tabMarket: 'Market',
  tabPaper: 'Paper book MNQ',
  loading: 'Loading the roll calendar.',
  failed: 'The roll calendar could not be read: {detail}',
  paperLoading: 'Loading the paper book roll schedule.',
  paperFailed: 'The paper book roll schedule could not be read: {detail}',
  paramCalendar: 'Calendar settings',
  paramMarket: 'Market settings',
  year: 'Year',
  allYears: 'All years',
  market: 'Market',
  asOf: 'As of',
  monthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  stripCaption: 'Rolls by month, {year}: {cells}',
  stripCaptionYear: 'each cell is the gap in percent of the roll that month',
  stripCaptionAll: 'each cell counts the in-sample rolls in that calendar month',
  stripCols: { n: 'No', ticker: 'Ticker', name: 'Name', rolls: 'Rolls' },
  stripOpen: 'Show the rolls of {root}',
  cellNone: '{root} {month} {year}: no roll',
  cellOne: '{root} {month} {year}: roll on {date}, gap {gap}',
  cellMany: '{root} {month} {year}: {count} rolls ({dates})',
  cellAll: '{root} {month}, all years: {count} rolls',
  cellManyText: '{count}x',
  numberedMarket: '{root} rolls',
  summary: '{root}: {count} rolls from {first} to {last}; mean absolute gap {mean}, largest {max}.',
  qaMatch: 'QA report count {total}: matches.',
  qaMismatch: 'QA report count {total}: differs from the {count} rolls shown.',
  qaAbsent: 'QA report count: not available.',
  qaSource: 'QA reference: {source}',
  chartName: '{root} roll gap in percent, {count} rolls',
  chartEmpty: '{root}: no roll in the served sample',
  chartSummary: '{name}: from {first} to {last}; smallest {min} on {minDate}, largest {max} on {maxDate}.',
  chartTableCaption: '{root} roll gaps',
  fenceLabel: 'IS | 2022+ SPENT',
  fenced: '{count} rolls dated after 2021-12-31 were not shown.',
  rollsCaption: '{root} rolls, oldest first',
  rollCols: {
    n: 'No',
    date: 'Roll date',
    lastDate: 'Last on old',
    from: 'From id',
    to: 'To id',
    close: 'Close before',
    gapPts: 'Gap pts',
    gapPct: 'Gap %',
  },
  idsNote: 'From id and to id are the vendor instrument ids; nq-lab records no contract code for them.',
  paperTitle: 'Paper book MNQ roll schedule',
  paperCaption: 'MNQ contracts around the one the book holds, oldest first',
  paperCols: { contract: 'Contract', expiry: 'Expiry', rollDate: 'Roll date', into: 'Into', status: 'Status' },
  paperStatus: { past: 'Past', held: 'Held', upcoming: 'Upcoming' } as Readonly<Record<string, string>>,
  paperHeld: 'Held after the close of {today} (New York): {held}; next roll {roll}.',
  paperRollToday: 'Today is a roll day: the book rolls at the close.',
  paperRule: 'Rule: {rule}.',
  paperSource: 'Source: {source}. Dates only; no price is read.',
  exportName: 'rolls',
  missingValue: '--',
} as const
