// Copy for RUNS and RUN (UI_SPEC sections 6, 7, 10; look spec 7.4). UK spelling, no em or en dashes,
// sentence case; uppercase only where the data is uppercase. `{name}` slots are filled by fillCopy().

/** The honesty tags of UI_SPEC section 6, verbatim. */
export const RUN_TAGS = {
  probe: '[PROBE: never a result]',
  anchor: '[ANCHOR]',
  ledgered: '[LEDGERED]',
  unusableBalance: '[UNUSABLE: BALANCE]',
  unusable: '[UNUSABLE]',
  unreadable: '[UNREADABLE]',
  postHoc: '[POST HOC]',
} as const

export const BADGE = {
  ok: '[OK]',
  fail: '[FAIL]',
  missing: '[NOT RECORDED]',
  checkOk: 'ok',
  checkFail: 'FAIL',
  none: '--',
} as const

export const RUNS = {
  title: 'Runs',
  gridLabel: 'Nautilus runs, {n} shown',
  filterLabel: 'Filter runs',
  filterPlaceholder: '<Enter filter>',
  strategyLabel: 'Strategy',
  strategyAll: 'All',
  tabsLabel: 'Run sets',
  paramsLabel: 'Run filters',
  tabs: { all: 'All', ledgered: 'Ledgered', anchors: 'Anchors', probes: 'Probes', unusable: 'Unusable' },
  basisNote: 'Sharpe and max drawdown: Basis B (account, compounded from K), one row per gated session, the tear sheet series. [POST HOC]',
  loading: 'Reading the runs.',
  failed: 'The runs could not be read: {detail}',
  statsFailed: 'Sharpe and max drawdown could not be read: {detail}',
  statsLoading: 'Reading Sharpe and max drawdown.',
  empty: 'No runs match. Clear the filter or pick 85) All.',
  none: 'No runs yet: backtests/output/*/result.json',
  counts: 'Runs {n}  Usable {usable}  Ledgered {ledgered}',
  cols: {
    runId: 'Run id',
    strategy: 'Strategy',
    kind: 'Kind',
    variant: 'Variant',
    window: 'Window',
    trades: 'Trades',
    pnl: 'Net P&L (USD)',
    fees: 'Fees (USD)',
    hitRate: 'Hit rate',
    sharpe: 'Sharpe (B)',
    maxDd: 'Max DD (B)',
    balance: 'Balance',
    mtm: 'MTM',
    coverage: 'Coverage',
    anchor: 'Anchor of',
    tags: 'Tags',
  },
  window: '{start} to {end}',
} as const

export const RUN = {
  title: 'Backtest: strategy analysis',
  fieldLabel: 'Run id',
  fieldPlaceholder: '<Run id>',
  noRun: 'Type a run id, then RUN (for example nt_dtsmom_v0_ts1 RUN), or open a row of RUNS.',
  loading: 'Reading {run}.',
  failed: '{run} could not be read: {detail}',
  tabsLabel: 'Run views',
  tabs: {
    chart: 'Chart',
    trades: 'Trades',
    fills: 'Fills',
    decisions: 'Decisions',
    closes: 'Closes',
    rolls: 'Rolls',
    config: 'Config',
    notes: 'Notes',
  },
  anchor: 'Anchor {verdict}',
  checks: { balance: 'Balance', mtm: 'MTM', coverage: 'Coverage' },
  anchorOf: 'base {base}',
  header: {
    label: 'Run facts',
    nautilus: 'Nautilus',
    elapsed: 'Elapsed',
    elapsedValue: '{s} s',
    venue: 'Venue',
    fillModel: 'Fill model',
    costPerSide: 'Cost per side (USD)',
    window: 'Window',
    variant: 'Variant',
  },
  ledger: {
    label: 'Ledger',
    command: 'Ledger command (copy only; the terminal never runs it)',
    cwd: 'Run from {cwd}',
    copy: 'Copy',
    copyLabel: 'Copy the ledger command',
    copied: 'Ledger command copied.',
    copyFailed: 'The browser refused the clipboard: select the command and copy it by hand.',
    placeholder: '<exp> is a placeholder: put the experiment id in its place before running.',
    notEligible: 'No ledger command: {reasons}',
    ledgered: '[LEDGERED] {exp} at {ts}',
  },
  chart: {
    label: 'Equity and drawdown',
    title: '{run} equity and underwater, Basis B',
    equity: '{run} equity (USD)',
    bench: 'Benchmark equity (USD)',
    underwater: '{run} underwater',
    benchUnderwater: 'Benchmark underwater',
    basis: 'Basis {basis}, {label}. Equity in {unit}. {source}.',
    bench_label: 'Benchmark: {label}.',
    noBench: 'No benchmark for this run.',
    dropped: 'Sessions dropped by the day gate: {n}.',
    loading: 'Reading the equity series.',
    failed: 'The equity series could not be read: {detail}',
    unusable: 'No equity line for an unusable run (rule 4).',
  },
  stats: {
    label: 'Statistics',
    caption: 'Statistics for {run}',
    metric: 'Summary',
    total: 'Total',
    trades: 'Trades',
    pnl: 'Net P&L (USD)',
    fees: 'Fees (USD)',
    hitRate: 'Hit rate',
    meanNetR: 'Mean net R',
    tNetR: 't (net R)',
    tPnl: 't (P&L per trade)',
    sharpe: 'Sharpe (B, annualised)',
    maxDd: 'Max drawdown (B)',
    sessions: 'Sessions (B)',
    note: 'Trade figures from result.json summary; Sharpe and drawdown [POST HOC] on Basis B.',
  },
  trades: {
    label: 'Trades of {run}, {n} rows',
    date: 'Date',
    side: 'Side',
    long: 'Long',
    short: 'Short',
    entryTs: 'Entry time',
    entryPx: 'Entry px',
    exitTs: 'Exit time',
    exitPx: 'Exit px',
    reason: 'Reason',
    pnlPts: 'P&L (pts)',
    pnlUsd: 'P&L (USD)',
    commission: 'Costs (USD)',
    netR: 'Net R',
    empty: 'This run has no trades.',
  },
  fills: {
    label: 'Fills of {run}, {n} rows',
    ts: 'Time (UTC)',
    instrument: 'Instrument',
    side: 'Side',
    qty: 'Qty',
    px: 'Price',
    commission: 'Commission',
    position: 'Position id',
    orderRef: 'Order ref',
    tags: 'Tags',
    empty: 'This run records no fills.',
  },
  log: {
    label: '{section} log of {run}, {n} rows',
    absent: 'This run has no {section} log.',
    empty: 'The {section} log is empty.',
  },
  page: {
    loading: 'Reading the rows.',
    label: 'Rows {from} to {to} of {total}',
    prev: 'Previous page',
    next: 'Next page',
  },
  config: {
    label: 'Configuration',
    sections: {
      config: 'Run configuration',
      venue: 'Venue',
      data: 'Data',
      summary: 'Summary statistics',
      coverage: 'Coverage check',
      logMeta: 'Strategy log',
      skipped: 'Skipped by the strategy',
    },
    empty: 'Not recorded.',
  },
  actions: {
    tearSheet: 'Open the tear sheet (EQ)',
    runs: 'Back to RUNS',
    copyLedger: 'Copy the ledger command',
  },
} as const

export const HELP_LINES = {
  runs: 'RUNS HELP',
  run: 'RUN HELP',
} as const
