// Copy for SEAS, seasonality (TASKS Phase 11; UI_SPEC 5 and 6; look spec 4.4, 6 and 7). UK spelling,
// no em or en dashes, sentence case. `{name}` slots are filled by fillCopy(). Every panel is
// descriptive and post hoc: no copy here may name a test, a p-value or a verdict.

export const SEAS = {
  title: 'Seasonality',
  field: 'Instrument or hypothesis',
  placeholder: '<NQ or a hypothesis>',
  helpLine: 'SEAS HELP',
  empty: 'Give an instrument or a registered hypothesis: {NQ SEAS <GO>} or {volmanaged_v0 SEAS <GO>}.',
  loading: 'Loading the seasonality of {name}.',
  failed: 'The seasonality of {name} could not be read: {detail}',
  paramLabel: 'Seasonality settings',
  from: 'From',
  to: 'To',
  variant: 'Variant',
  variantOptions: { auto: 'Default', vendor: 'Vendor', repaired: 'Repaired' },
  cost: 'Cost',
  costOption: '{n} tick(s)',
  sessions: 'Sessions',
  span: '{first} to {last}',
  noSpan: 'no session in the years picked',
  tabsLabel: 'Seasonality views',
  tabs: {
    month: 'Month',
    weekday: 'Weekday',
    week_of_month: 'Week of month',
    intraday: '30 minutes',
    heatmap: 'Month by year',
  },
  panelName: {
    month: '{subject} mean monthly {measure} by calendar month',
    weekday: '{subject} mean session {measure} by weekday',
    week_of_month: '{subject} mean session {measure} by week of month',
    intraday: '{subject} mean 30-minute {measure} by bucket of the NYSE session (ET)',
  },
  heatName: '{subject} monthly {measure}, years by months',
  measureReturn: 'return',
  measurePnl: 'P&L',
  whiskers: 'band of the mean plus and minus one standard error (a spread of the mean, not a confidence interval)',
  gridLabel: '{name}: n, mean, standard error and hit rate per group',
  cols: { group: 'Group', n: 'n', mean: 'Mean', se: 'Std error', lo: 'Mean - 1 se', hi: 'Mean + 1 se', hit: 'Hit rate' },
  unavailable: 'Not shown: {note}.',
  observation: 'One n is {observation}.',
  excluded: '{count} sessions left out of the 30-minute buckets ({source}).',
  excludedNone: 'No session left out of the 30-minute buckets ({source}).',
  pick: 'Row {label}: mean {mean}, one standard error {se}, hit rate {hit}, n {n}.',
  pickNone: 'Row {label}: no value (n 0).',
  errorBar: 'Bars: {text}.',
  units: 'Units: {unit}.',
  unitsPercent: 'Values in percent of the previous price, 2 decimals; hit rate is the share above zero.',
  unitsCapital: 'Values in percent of capital, 2 decimals; hit rate is the share above zero.',
  unitsUsd: 'Values in USD, 0 decimals; hit rate is the share above zero.',
  aggregation: { compound: 'Months compound their session returns.', sum: 'Months sum their session values (screen basis).' },
  intradayScale: 'This panel shows basis points of the previous price, 2 decimals (1 bp is 0.01%): 30-minute moves are small.',
  heatNote: 'A blank cell is a month with no session in the years picked. The month tab averages these cells across years.',
  noPValue: 'Descriptive only: no test and no p-value on a picked slice.',
  exportName: 'seasonality',
  actionsGp: 'Open GP for this instrument',
  actionsDes: 'Open DES for this hypothesis',
} as const
