// Copy for the analytics tear sheet (TASKS 6.4; UI_SPEC section 7 "Analytics tear sheet"; look spec
// 7.5): five tabs in one panel, plus the run books of a run. UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy().

export const TEAR = {
  tabsLabel: 'Performance views',
  tabs: { EQ: 'Equity', DD: 'Drawdown', RET: 'Returns', RR: 'Rolling', MRET: 'Monthly' },
  titles: {
    EQ: 'Performance: equity curve',
    DD: 'Performance: drawdown',
    RET: 'Performance: returns and risk',
    RR: 'Performance: rolling statistics',
    MRET: 'Performance: monthly returns',
  },
  paramsLabel: 'Tear sheet parameters',
  fieldLabel: 'Hypothesis or run',
  fieldPlaceholder: '<Hypothesis or run>',
  run: 'Run',
  hypothesis: 'Hypothesis',
  versus: 'vs',
  noBenchmark: 'no benchmark',
  range: 'Range',
  rangeValue: '{first} to {last}',
  sessions: 'n',
  freq: 'Freq',
  freqDaily: 'Daily',
  freqMonthly: 'Monthly',
  cost: 'Cost',
  costTicks: '{n} tick per side',
  costTicksPlural: '{n} ticks per side',
  basis: 'Basis',
  basisLine: 'Basis {basis}: {label}. Unit: {unit}.',
  basisShort: 'Basis {basis}',
  percentOf: 'percent ({unit}, times 100)',
  dropped: '{n} sessions dropped by the day gate.',
  kpisLabel: 'Tear sheet key figures',
  kpiDescription: '{label}. Unit as the API states it: {unit}. Tag {tag}.',
  kpiPercent: 'Shown as a percentage: the API value times 100.',
  loading: 'Loading the tear sheet.',
  loadingBooks: 'Loading the run books.',
  needContext: 'This screen needs a run or a hypothesis. Type one before the mnemonic, for example {example}.',
  needContextExample: 'volmanaged_v0 EQ',
  wrongContext: 'The tear sheet takes a run or a hypothesis, not the {kind} {value}.',
  refused: 'The server refused this tear sheet: {detail}',
  unusableTag: 'UNUSABLE: BALANCE',
  unusable: 'The balance check failed, so this run is unusable and nothing is drawn (rule 4).',
  failed: 'The tear sheet could not be read: {detail}',
  noSeries: 'No return series is recorded for {name}, so there is nothing to draw.',
  checkRow: 'No return series: this row is a check inside {parent}.',
  checkRowOpen: "Open {parent}'s tear sheet:",
  /** A command link (`{<line> <GO>}`): the parent on the open tab. */
  checkRowLink: '{{parent} {code} <GO>}',
} as const

export const TEAR_BAR = {
  actions: 'Actions',
  help: 'Help',
  related: 'Related functions',
  back: 'Back',
  forward: 'Forward',
  openRun: 'Run inspector (RUN)',
  openDes: 'Hypothesis description (DES)',
  export: 'Export',
} as const

export const TEAR_EQ = {
  title: '{name} equity',
  strategy: '{name}',
  benchmark: 'Benchmark',
  benchmarkNone: 'No benchmark for this series.',
  diffMissing: 'Performance difference pane not shown: the API sends no strategy minus benchmark series.',
  perfDiff: 'Performance difference (strategy minus benchmark)',
  diffUnit: 'Lower pane: performance difference, {unit}, in percent (times 100).',
} as const

export const TEAR_DD = {
  title: '{name} drawdown',
  equity: '{name}',
  benchmark: 'Benchmark',
  underwater: 'Underwater',
  benchUnderwater: 'Benchmark underwater',
  maxLine: 'Max drawdown {value}; benchmark {bench}.',
  tableCaption: 'Top drawdowns, deepest first (DD2)',
  tableEmpty: 'No drawdown episodes.',
  cols: { rank: '#', peak: 'Peak', trough: 'Trough', recovery: 'Recovery', depth: 'Depth', toTrough: 'To trough', toRecovery: 'To recovery', length: 'Length' },
  start: 'start',
  open: 'open',
  lengthUnit: 'Lengths in {unit}.',
} as const

export const TEAR_RR = {
  title: '{name} rolling statistics',
  sharpe: 'Sharpe {n} {unit}',
  vol: 'Vol {n} {unit}',
  full: 'Full sample: Sharpe {sharpe}, volatility {vol}.',
  units: { sessions: 'sessions', months: 'months' },
  sharpePane: 'Rolling Sharpe',
  volPane: 'Rolling volatility',
  needs: 'Needs {window} {unit}; this series has {n}.',
  longNeeds: 'The {window}-{one} lines need {window} {unit}; this series has {n}.',
  one: { sessions: 'session', months: 'month' },
  hi: 'Hi: {value}',
  lo: 'Low: {value}',
  extremes: '{window} {unit}: Hi {hi} on {hiDate}, Low {lo} on {loDate}.',
  extremesNone: '{window} {unit}: no rolling value.',
  extremesLabel: 'Rolling volatility extremes',
} as const

export const TEAR_MRET = {
  heatmapName: '{name} monthly returns',
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  aggregation: 'Aggregation: {text}.',
  yearlyName: '{name} yearly totals (house addition, not in the reference layout)',
  average: 'The first row [POST HOC] is the average of each month over the years shown, computed by the terminal. Cells print percent without the % sign.',
  yearlyNote: 'Yearly totals below, in percent: a house addition, not in the reference layout.',
} as const

export const TEAR_RET = {
  histogramName: '{name} return distribution',
  binRule: 'Bins: {rule}.',
  seriesNote: 'Left: each period\'s return ({unit}) on the same axis as the histogram.',
  statsLabel: 'Return statistics',
  summary: 'Summary',
  risk: 'Risk ({horizon}, positive values are losses)',
  validity: 'Validity',
  rows: {
    n: 'Observations',
    years: 'Years',
    hitRate: 'Hit rate (non-zero periods)',
    bestDay: 'Best period',
    worstDay: 'Worst period',
    bestMonth: 'Best month',
    worstMonth: 'Worst month',
    pctPositiveMonths: 'Positive months',
    skew: 'Skew',
    excessKurtosis: 'Excess kurtosis',
    var95: 'VaR 95',
    cvar95: 'CVaR 95',
    var99: 'VaR 99',
    cvar99: 'CVaR 99',
    tails5: '{window} period tail, 5% mean shortfall',
    tails1: '{window} period tail, 1% mean shortfall',
    tailsN: '{window} period windows',
    sharpe: 'Sharpe',
    ci: '95% interval',
    psrZero: 'PSR (0)',
    benchSharpe: 'Benchmark Sharpe',
    psrBench: 'PSR (benchmark Sharpe)',
    minTrlZero: 'MinTRL (0)',
    minTrlBench: 'MinTRL (benchmark Sharpe)',
    actual: 'Track record',
  },
  /** G16: the 21-session tail rows get their own section (overlapping sums are losses when negative,
   * the opposite sign convention from the VaR/CVaR rows above them). */
  tailsTitle: '{window}-session loss (overlapping sums, negative = loss)',
  tailsNote: 'With only {n} windows, the 5% and 1% tails fall on the same window and cannot be told apart.',
  ciValue: '{lo} to {hi}',
  periods: '{n} {unit}',
  reasons: {
    reachable: 'reachable',
    below_threshold: 'not reachable',
    undefined: 'not defined',
  },
  /** One note under the stats table per reason, naming the rows it explains. */
  reasonNotes: {
    reachable: '',
    below_threshold: 'Not reachable: the Sharpe is at or below the threshold ({rows}).',
    undefined: 'Not defined: the return moments give no track record length ({rows}).',
  },
  psrBenchNote: 'Note: {note}.',
} as const

/**
 * SV7 on RET (ANALYTICS_CATALOG SV7 and C4): the Ledoit-Wolf and Memmel tests of the Sharpe difference
 * against buy and hold, read from the screen file per cost and never recomputed. `title` is the fallback
 * when the rows do not share the file's own label.
 */
export const TEAR_SV7 = {
  title: 'Sharpe difference (m - BH)',
  /** G07: fixed, never the series tag. The card's numbers are read from the screen file (a registered
   * result, SV7's own basis text below), so they are [PRE-REG] regardless of whether the series itself
   * is tagged [POST HOC] or [PRE-REG]. */
  tag: '[PRE-REG]',
  regionLabel: 'Sharpe difference tests',
  basis: "Read from the screen file, never recomputed: the annualised Sharpe of the strategy minus buy and hold's, per cost in ticks per side, on the file's own sample (Observations below).",
  chartName: '{name} {label} by cost, Ledoit-Wolf, annualised',
  ci: '90% interval (Ledoit-Wolf bootstrap)',
  caption: '{label} by cost, as the screen file records it',
  cost: '{n} tick',
  costPlural: '{n} ticks',
  measure: 'Measure',
  bands: {
    lw: 'Ledoit-Wolf, annualised',
    memmel: 'Memmel',
    provenance: 'Provenance (Ledoit-Wolf bootstrap)',
  },
  rows: {
    headline: 'Screen headline',
    point: 'Difference',
    se: 'Standard error',
    lo: '90% low',
    hi: '90% high',
    lwP: 'Ledoit-Wolf p',
    z: 'Memmel z',
    rho: 'Memmel rho',
    memmelP: 'Memmel p',
    block: 'Block length',
    reps: 'Replications',
    seed: 'Seed',
    n: 'Observations',
  },
  pNote: "Both p-values are one-sided, on the file's whole sample, never on a slice.",
  notRecorded: 'Sharpe difference (m - BH): not recorded for this series.',
  droppedOne: '1 entry in another shape was left out.',
  dropped: '{n} entries in another shape were left out.',
  allDroppedOne: 'Sharpe difference (m - BH): 1 entry in another shape was left out, so nothing is drawn.',
  allDropped: 'Sharpe difference (m - BH): {n} entries in another shape were left out, so nothing is drawn.',
} as const

export const TEAR_BOOKS = {
  heading: 'Run books',
  headingLabel: 'Run books of {run}',
  tradesTitle: 'Trades',
  costsTitle: 'Costs',
  exposureTitle: 'Exposure and turnover',
  noTrades: 'This run has no closed trades, so it has no trade panels.',
  tradeStatsLabel: 'Trade statistics',
  tradeRows: {
    n: 'Trades',
    wins: 'Wins',
    losses: 'Losses',
    winRate: 'Win rate',
    profitFactor: 'Profit factor',
    expectancy: 'Expectancy',
    avgWin: 'Average win',
    avgLoss: 'Average loss',
    payoff: 'Payoff',
    maxWin: 'Largest win',
    maxLoss: 'Largest loss',
    totalPnl: 'Total P&L',
    meanNetR: 'Mean net R (stored)',
    tNetR: 't of net R (stored)',
    hitStored: 'Stored hit rate',
  },
  hitMatch: 'Stored hit rate matches the win rate.',
  hitMismatch: 'Stored hit rate differs from the win rate.',
  groupLabel: 'Group P&L by',
  groups: { hour: 'Entry hour', weekday: 'Weekday', month: 'Month' },
  groupName: '{run} mean P&L per trade by {group}',
  groupCi: '{ci}',
  groupUnit: 'Unit: {unit}, {timezone}.',
  slippageTitle: 'Fill slippage (real fills only)',
  slippageQuote: 'Fill slippage, real fills of the za_orb quote-check sample (results/quote_check_v1.json), {unit}',
  slippageLive: 'Fill slippage, real fills of the paper book close rows ({journal}, volmanaged on MNQ), {unit}',
  slippageNone: 'No real-fill sample belongs to {strategy}: the quote check is a za_orb sample and the paper book trades volmanaged on MNQ, so neither is shown here. Backtest fills are modelled and have no slippage distribution.',
  strategyUnknown: 'this run',
  slippageCols: { name: 'Group', n: 'n', mean: 'Mean', p5: 'P5', p50: 'P50', p95: 'P95', source: 'Source' },
  slippagePlumbing: '{n} plumbing rows left out of the live rows.',
  waterfallCaption: 'Cost waterfall (EX3), {unit}',
  waterfallCols: { step: 'Step', value: 'Value' },
  sidesLine: '{sides} contract sides at {ticks} ticks modelled slippage.',
  sidesLineOne: '{sides} contract sides at 1 tick modelled slippage.',
  sensitivityName: '{run} net P&L against slippage ticks per side',
  breakEven: 'break-even {ticks} ticks',
  breakEvenNone: 'No break-even inside 0 to 4 ticks (break-even {ticks} ticks).',
  runTicks: 'The run charged {ticks} ticks per side.',
  tickLabel: '{n} t',
  exposureName: '{run} exposure and turnover',
  exposureUnit: '{label}. Unit: {unit}.',
  exposureUnitTurnover: '{label}. Unit: {unit}; turnover: {turnover}.',
  gross: 'Gross exposure',
  net: 'Net exposure',
  turnover: 'Turnover',
  exposureMeans: 'Mean gross {gross}, mean net {net}; turnover {daily} per session, {annual} a year.',
  priceBasis: 'Price basis: {text}.',
  reconcile: 'Positions reconcile with the fills.',
  noReconcile: 'Positions do not reconcile with the fills.',
  unavailable: 'No exposure panel: {note}',
  failed: 'Could not read this panel: {detail}',
} as const

export const TEAR_GALLERY = {
  runTitle: 'Tear sheet of a run',
  hypothesisTitle: 'Tear sheet of a hypothesis',
  unusableTitle: 'Tear sheet of an unusable run',
  sv7Title: 'Returns tab of a hypothesis with its Sharpe difference card',
} as const
