// Copy for the P1 views of the analytics tear sheet (TASKS Phase 10 on screen; ANALYTICS_CATALOG SV5, SV6,
// PF7 to PF9, RK3, RD3, RD4, RK5, RL3, RL4, BR3, BR4, RG1, TA2, TA4, TA5). UK spelling, no em or en dashes.
// `{name}` slots are filled by fillCopy(). Every panel here is [POST HOC]: computed by the terminal,
// descriptive, in sample, never a registered test and never a verdict.

export const TEAR_P1 = {
  heading: 'Extended analytics',
  headingLabel: 'Extended analytics for {name}',
  descriptive: 'Descriptive, in sample, not a registered test.',
  loading: 'Reading the extended analytics.',
  failed: 'Not available: {detail}',
  bootstrap: {
    title: 'Bootstrap intervals (SV5)',
    line: '{method}. Block length {block} (stationary, Politis-White), {reps} replications, seed {seed}, {confidence} percentile interval.',
    caption: 'Bootstrap intervals by statistic',
    cols: { statistic: 'Statistic', point: 'Sample', interval: 'Interval', median: 'Median', sd: 'SD' },
    undefinedNote: '{label}: {n} replications where it is not defined, left out and counted.',
    intervalValue: '{lo} to {hi}',
    mertens: 'The Sharpe tile above keeps the Mertens interval (P0); these intervals come from resampling.',
    tooShort: 'No bootstrap: the block length needs at least {min} observations and this series has {n}.',
  },
  cone: {
    title: 'Resampled cone (SV6)',
    name: '{name} resampled paths',
    basis: 'Unit: {unit}, paths {how}. Pointwise percentiles 5, 25, 50, 75 and 95 at each step, not a band that whole paths stay inside: each is taken over the same replications at that horizon alone. The realised last {horizon} steps in orange.',
    summed: 'summed',
    compounded: 'compounded',
  },
  band: {
    low: 'Range low, Sharpe {n} {unit}',
    high: 'Range high, Sharpe {n} {unit}',
    window: 'a {n}-{one} Sharpe, {lo} to {hi}',
    join: ', and of ',
    note: 'Dashed amber lines: the range (95%) of {windows}, if the full-sample Sharpe {sharpe} held throughout (Mertens standard error). A line outside its range is not by itself a regime change.',
  },
  ratios: {
    title: 'Ratios (PF7 to PF9)',
    label: 'Omega, tail ratio and gain to pain',
  },
  cf: {
    title: 'Normal and Cornish-Fisher VaR (RK3)',
    caption: 'Normal and Cornish-Fisher VaR by level, {horizon}, a positive loss',
    cols: { level: 'Level', normal: 'Normal', historical: 'Historical (RK1)', cornishFisher: 'Cornish-Fisher', raw: 'Raw expansion', value: 'Shown', used: 'Method' },
    usedCf: 'Cornish-Fisher',
    usedHistorical: 'historical: Cornish-Fisher not defined here',
    notDefined: 'not defined',
    moments: 'Population moments: mean {mean}, sigma {sigma}, skew {skew}, excess kurtosis {kurt}.',
  },
  jb: {
    title: 'Normality (RD3, RD4)',
    caption: 'Jarque-Bera on the whole series',
    statistic: 'Jarque-Bera statistic',
    p: 'p-value (whole series)',
    n: 'Observations',
    qqName: '{name} QQ plot',
    qqX: 'Normal quantile',
    qqY: 'Ordered return',
    qqLine: 'fit',
    qqSlopePercent: '% per unit z',
    qqSlopeUnit: ' per unit z',
  },
  stress: {
    title: 'Stress windows (RK5)',
    caption: 'Frozen stress windows, peak to trough of NQ buy and hold',
    cols: { window: 'Window', dates: 'Peak to trough', covered: 'Rows held', nq: 'NQ depth', strategy: 'Strategy', bench: 'Benchmark', maxDd: 'Strategy max DD', n: 'Rows' },
    basis: '{frozen}. Basis {basis}, unit: {unit}.',
    spentTag: '[SPENT]',
    spentNote: 'Spent window, opened 2026-09-26, descriptive only.',
    window: '{peak} to {trough}',
  },
  relative: {
    title: 'Rolling beta and correlation (RL3, RL4)',
    name: '{name} rolling beta and correlation',
    beta: 'Beta, {window} {unit}',
    correlation: 'Correlation, {window} {unit}',
    full: 'Full sample: beta {beta}, correlation {correlation}.',
    needs: 'Rolling beta and correlation need {window} {unit} with a benchmark; this series has {n}, so there is no rolling value to draw.',
  },
  capture: {
    title: 'Up and down capture (BR3)',
    caption: 'Up and down capture, annualised geometric',
    up: 'Up capture',
    down: 'Down capture',
    upN: 'Benchmark-up {unit}',
    downN: 'Benchmark-down {unit}',
    unitSessions: 'sessions',
    unitMonths: 'months',
  },
  scatter: {
    title: 'Strategy against benchmark (BR4)',
    name: '{name} against its benchmark',
    x: 'Benchmark',
    y: 'Strategy',
    line: 'OLS (BR1)',
    axes: 'x: {x}. y: {y}. Unit: {unit}.',
  },
  regimes: {
    title: 'Volatility regimes (RG1)',
    caption: 'Terciles of NQ realised variance known the session before',
    cols: { regime: 'Regime', n: 'Sessions', mean: 'Mean', sharpe: 'Sharpe', hit: 'Hit rate' },
    names: { low: 'Low', mid: 'Mid', high: 'High' },
    welch: 'Welch t, high against low: {t} (df {df}).',
    noP: 'No p-value: a fixed split, still [POST HOC].',
    unlabelled: 'Sessions without a regime (fewer than {min} earlier values): {n}.',
  },
  none: 'Not shown: {note}',
} as const
