// Copy for the trade paths card of a run's tear sheet (ANALYTICS_CATALOG TA2, TA4, TA5). UK spelling, no em
// or en dashes. `{name}` slots are filled by fillCopy().

export const TRADE_PATHS = {
  title: 'Trade paths (TA2, TA4, TA5)',
  loading: 'Reading the trade paths.',
  failed: 'Not available: {detail}',
  win: 'win',
  loss: 'loss',
  maeName: '{name} MAE against the final result',
  mfeName: '{name} MFE against the final result',
  final: 'Final',
  mae: 'MAE',
  mfe: 'MFE',
  unitR: 'R',
  unitPts: 'pts',
  basis: 'In {unit}: {label}. Bars: {symbol}, {variant}, through the gate as caller terminal.',
  noBars: 'Trades with no 1-minute bar inside them: {n} (entry and exit prices only).',
  offBasisOne: '{n} of {checked} trades has a fill outside the 1-minute bars it could have happened in (more than one tick away); its MAE and MFE may be on another price basis.',
  offBasisMany: '{n} of {checked} trades have a fill outside the 1-minute bars they could have happened in (more than one tick away); their MAE and MFE may be on another price basis.',
  holdingName: '{name} holding time',
  holdingBin: '{lo} to {hi} min',
  holdingTitle: 'Holding time',
  holdingBasis: '{rule}; bars are counts of trades.',
  holdingCaption: 'Holding time summary',
  minutes: '{value} min',
  range: '{lo} to {hi} min',
  rows: {
    n: 'Trades',
    zero: 'Zero durations (counted apart)',
    median: 'Median',
    mean: 'Mean',
    p5: '5th percentile',
    p95: '95th percentile',
    range: 'Range',
    longestWin: 'Longest winning run',
    longestLoss: 'Longest losing run',
    wins: 'Winning trades',
    losses: 'Losing trades',
    runs: 'Runs',
    expected: 'Expected runs',
    z: 'Runs test z',
    p: 'Runs test p (whole list)',
  },
  streakCaption: 'Streaks and the runs test on the whole trade list',
} as const
