// Generates desktop/src-tauri/assets/look.css from the web app's tokens (web/src/theme/tokens.css), so the
// shell's own pages (splash, later stopped and rebuild) wear the terminal's look without a hand-edited colour.
// Node built-ins only; no package is installed under desktop/.
//
// Usage:
//   node desktop/scripts/copy-tokens.mjs           writes look.css
//   node desktop/scripts/copy-tokens.mjs --check   fails if look.css differs from a fresh copy, or if a text pair
//                                                  the shell pages use is below WCAG 2.2 AA (4.5:1 text, 3:1 focus)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { isMainModule } from './main-module.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const TERMINAL = path.resolve(HERE, '..', '..')
export const TOKENS = path.join(TERMINAL, 'web', 'src', 'theme', 'tokens.css')
export const LOOK = path.join(TERMINAL, 'desktop', 'src-tauri', 'assets', 'look.css')

// The tokens the shell pages use. Each must exist in tokens.css with a literal value.
export const SHELL_TOKENS = [
  '--font-sans', '--font-mono', '--fs-data', '--fs-small', '--fs-title', '--fs-kpi',
  '--bg', '--chrome', '--text', '--data', '--muted', '--border', '--focus', '--link', '--c-down', '--warn',
]

// Text and graphics pairs the shell rules below draw, with the WCAG 2.2 AA minimum each needs.
export const PAIRS = [
  ['--text', '--bg', 4.5], ['--data', '--bg', 4.5], ['--muted', '--bg', 4.5], ['--link', '--bg', 4.5],
  ['--c-down', '--bg', 4.5], ['--warn', '--bg', 4.5], ['--text', '--chrome', 4.5], ['--focus', '--bg', 3],
  ['--data', '--chrome', 3],
]

const RULES = `
html,
body {
  margin: 0;
  height: 100%;
  background: var(--bg);
  color: var(--text);
  font-family: var(--font-sans);
  font-size: var(--fs-data);
}

.shell-page {
  box-sizing: border-box;
  min-height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  padding: 0 12%;
  border-top: 4px solid var(--data);
}

.shell-page h1 {
  margin: 0 0 12px;
  font-size: var(--fs-kpi);
  font-weight: 700;
  color: var(--data);
  letter-spacing: 0.02em;
}

.shell-status {
  margin: 0 0 8px;
  padding: 4px 8px;
  background: var(--chrome);
  border-left: 3px solid var(--data);
  font-family: var(--font-mono);
}

.shell-note {
  margin: 0;
  color: var(--muted);
  max-width: 60ch;
}

.shell-error {
  color: var(--c-down);
}

.shell-page a {
  color: var(--link);
}

.shell-page :focus-visible {
  outline: 2px solid var(--focus);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
`

/** Every `--name: value;` declaration of tokens.css, the first LITERAL definition winning: the Tailwind
 * `@theme inline` block only maps names to var() references, and the default dark theme comes before the
 * colour-vision overrides. A name with no literal value keeps its first reference, which generate() refuses. */
export function declarations(css) {
  const out = new Map()
  const body = css.replace(/\/\*[\s\S]*?\*\//g, '')
  for (const m of body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;{}]+);/gi)) {
    const value = m[2].trim()
    const known = out.get(m[1])
    if (known === undefined || (known.includes('var(') && !value.includes('var('))) out.set(m[1], value)
  }
  return out
}

export function generate(css) {
  const all = declarations(css)
  const lines = []
  for (const name of SHELL_TOKENS) {
    const value = all.get(name)
    if (value === undefined) throw new Error(`token ${name} is missing from tokens.css`)
    if (value.includes('var(')) throw new Error(`token ${name} is not a literal value: ${value}`)
    lines.push(`  ${name}: ${value};`)
  }
  return [
    '/* GENERATED by desktop/scripts/copy-tokens.mjs from web/src/theme/tokens.css. Do not edit by hand:',
    '   change the tokens in the web app and run the script again (check.ps1 runs it with --check). */',
    '',
    ':root {',
    ...lines,
    '  color-scheme: dark;',
    '}',
    RULES,
  ].join('\n')
}

function channel(c) {
  const v = c / 255
  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4
}

export function luminance(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex)
  if (!m) throw new Error(`not a #rrggbb colour: ${hex}`)
  const n = parseInt(m[1], 16)
  return 0.2126 * channel((n >> 16) & 255) + 0.7152 * channel((n >> 8) & 255) + 0.0722 * channel(n & 255)
}

export function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

/** The pairs below their minimum, as readable strings. */
export function contrastFailures(css) {
  const all = declarations(css)
  return PAIRS.flatMap(([fg, bg, min]) => {
    const ratio = contrast(all.get(fg), all.get(bg))
    return ratio + 1e-9 < min ? [`${fg} on ${bg}: ${ratio.toFixed(2)}:1, needs ${min}:1`] : []
  })
}

function main(argv) {
  const css = fs.readFileSync(TOKENS, 'utf8')
  const fresh = generate(css)
  const failures = contrastFailures(css)
  if (failures.length) {
    console.error('contrast below WCAG 2.2 AA:\n  ' + failures.join('\n  '))
    return 1
  }
  if (argv.includes('--check')) {
    const current = fs.existsSync(LOOK) ? fs.readFileSync(LOOK, 'utf8') : ''
    if (current !== fresh) {
      console.error(`${LOOK} is not a fresh copy of the tokens: run node desktop/scripts/copy-tokens.mjs`)
      return 1
    }
    console.log(`look.css matches tokens.css; ${PAIRS.length} contrast pairs pass`)
    return 0
  }
  fs.writeFileSync(LOOK, fresh, 'utf8')
  console.log(`wrote ${LOOK}`)
  return 0
}

if (isMainModule(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2))
}
