// pnpm gen:api    regenerates src/api/schema.d.ts and src/api/openapi.sha256 from terminal/contract/openapi.json
// pnpm check:api  exits 1 when either file is stale (the same check as src/api/contractSync.test.ts)
//
// Safe to re-run at any time: the output depends only on the contract file. The sha256 is taken over the
// contract with CRLF normalised to LF (see src/api/contractSync.ts), and is written both to openapi.sha256
// and to the first line of schema.d.ts, so a stale copy of either is caught.
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const API_DIR = new URL('../', import.meta.url)
const CONTRACT = new URL('../../../../contract/openapi.json', import.meta.url)
const SCHEMA = new URL('schema.d.ts', API_DIR)
const SHA_FILE = new URL('openapi.sha256', API_DIR)
const HEADER_PREFIX = '// contract sha256: '

const normalise = (text) => text.replace(/\r\n/g, '\n')
const sha256 = (text) => createHash('sha256').update(normalise(text), 'utf8').digest('hex')

async function render(contractText, sha) {
  const ast = await openapiTS(JSON.parse(contractText), { alphabetize: false, exportType: false })
  const body = normalise(astToString(ast))
  const header = [
    `${HEADER_PREFIX}${sha}`,
    '// Generated by `pnpm gen:api` (openapi-typescript) from terminal/contract/openapi.json.',
    '// Never edit by hand: change the backend, refresh the contract snapshot, then re-run `pnpm gen:api`.',
    '',
  ].join('\n')
  return `${header}${body}`
}

async function readOrEmpty(url) {
  try {
    return await readFile(url, 'utf8')
  } catch {
    return ''
  }
}

async function main() {
  const check = process.argv.includes('--check')
  const contractText = await readFile(CONTRACT, 'utf8')
  const sha = sha256(contractText)
  const schemaText = await render(contractText, sha)
  if (check) {
    const [schemaNow, shaNow] = await Promise.all([readOrEmpty(SCHEMA), readOrEmpty(SHA_FILE)])
    const stale = []
    if (normalise(schemaNow) !== schemaText) stale.push(fileURLToPath(SCHEMA))
    if (shaNow.trim() !== sha) stale.push(fileURLToPath(SHA_FILE))
    if (stale.length > 0) {
      console.error(`stale generated API files (run pnpm gen:api):\n  ${stale.join('\n  ')}`)
      process.exit(1)
    }
    console.log(`API types in sync with the contract (sha256 ${sha})`)
    return
  }
  await writeFile(SCHEMA, schemaText, 'utf8')
  await writeFile(SHA_FILE, `${sha}\n`, 'utf8')
  console.log(`wrote ${fileURLToPath(SCHEMA)} and ${fileURLToPath(SHA_FILE)} (sha256 ${sha})`)
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
